src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Eyefinity_Access__c</fullName>
        <label>Eyefinity Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B - Basic</fullName>
                </value>
                <value>
                    <fullName>J - Participates in E-Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Calculation_Code__c</fullName>
        <label>Fee Calculation Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>O - Old Calculated Fee Schedule</fullName>
                </value>
                <value>
                    <fullName>N - New Calculated Fee Schedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Distribution__c</fullName>
        <description>Vision Care Practice receives one total payment or individual payments for each Business Account</description>
        <label>Payment Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Practice Account</fullName>
                </value>
                <value>
                    <fullName>Business Account(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>Practice Account Payment Method</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Business_Type__c</fullName>
        <label>Practice Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S - Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>C - Corporation</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction</fullName>
                </value>
                <value>
                    <fullName>P - Partnership</fullName>
                </value>
                <value>
                    <fullName>U - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>V - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>W - Applicant Doctor</fullName>
                </value>
                <value>
                    <fullName>X - Group Authorized Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Phone_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Location Phone Number</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Business_Account</fullName>
        <active>true</active>
        <description>A business entity doing business/providing a service or expressing an intent to do business/provide service with at least one VSP Global line of business.</description>
        <label>Business Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Practice_Account</fullName>
        <active>true</active>
        <description>A business entity representing the practice (identified by Tax ID) having a parent relationship over one or more Business Accounts.</description>
        <label>Practice Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Degree__c</fullName>
        <description>The educational degree of the Vision Care Doctor.</description>
        <inlineHelpText>The educational degree of the Vision Care Doctor.</inlineHelpText>
        <label>Degree</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OD</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doctor_ID__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Doctor ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doctor_Type__c</fullName>
        <label>Doctor Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Doctor</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>S - School Faculty Provider</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Provider (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender of the Vision Care Doctor.</description>
        <inlineHelpText>Gender of Contact.</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <description>National Provider Indicator for a Vision Care Doctor.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>National Provider Indicator for a Vision Care Doctor.</inlineHelpText>
        <label>NPI</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Eye_Care_Professional</fullName>
        <active>true</active>
        <label>Eye Care Professional</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fee_Calculation_Code__c</fullName>
        <formula>LEFT(TEXT( Account__r.Parent.Fee_Calculation_Code__c ), 1)</formula>
        <label>Fee Calculation Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/General_Table__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Table</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>General Table</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Doctor_ID__c</fullName>
        <description>Doctor ID of associated Contact record</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Doctor ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR33_CheckVSPnetworkProvider_Test.cls
@isTest
//Test class for VSPR25b_CheckVSPnetworkProvider
public class VSPR33_CheckVSPnetworkProvider_Test {
    
    @TestSetup
    static void testData(){
        
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@vsp.com';
        
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='VSP Network Recruitment User'];
        User u = new User(Alias = 'standt', Email='standarduser@vsp.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName=uniqueUserName);
        
        System.runAs(u){
            
            Account acc= new Account();
            acc.Name='Practice Account Name';
            acc.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
            acc.Tax_ID__c = '123456789';
            acc.Phone = '1234567890';
            acc.ShippingStreet = '123 Test Street';
            acc.ShippingCity = 'Somewhere';
            acc.ShippingState = 'CA';
            acc.ShippingPostalCode = '90210';
            acc.ShippingCountry = 'USA';
            acc.Practice_Business_Type__c = 'S - Sole Proprietor';
            acc.Fee_Calculation_Code__c = 'N - New Calculated Fee Schedule';
            acc.Payment_Method__c = 'Direct Deposit';
            acc.Payment_Distribution__c = 'Practice Account';
            Id practiceRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Practice_Account').getRecordTypeId();
            
            acc.RecordTypeId =  practiceRecordTypeId;        
            insert acc;
            system.debug('++++++++++++++++++++++++++++  TestClassAccId  ++++++++++++++++++++++++++++++++++++++++++++++' + acc.Id);
            
            Account acc1= new Account();
            Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
            acc1.Name='Business Account Name';       
            acc1.ParentId = acc.id;
            acc1.Fax = '123456789';
            acc1.ShippingStreet = '123 Test Street';
            acc1.ShippingCity = 'Somewhere';
            acc1.ShippingState = 'CA';
            acc1.ShippingPostalCode = '90210';
            acc1.ShippingCountry = 'USA';
            acc1.Vision_Care_Location_Phone_Number__c = '123456789';
            acc1.Eyefinity_Access__c = 'B - Basic';
            acc1.Location_Type__c = 'A - Affiliate Provider Location';
            acc1.Tax_ID__c = '123456789';
            acc1.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
            acc1.Vision_Care_End_Date__c = System.today() + 3;
            acc1.RecordTypeId =  businessRecordTypeId; 
            
            insert acc1;  
            
            
            /*         Id reacId;
List<General_Table__c> checkReac = new List<General_Table__c>([SELECT Id from General_Table__c WHERE Table__c = 'PRS6' AND Name = 'REAC' LIMIT 1]);
if(checkReac.size() == 0){
General_Table__c gt3 = new General_Table__c();
gt3.Name = 'REAC';
gt3.Table__c = 'PRS6';
gt3.Status__c = 'Active';
insert gt3;
reacId = gt3.Id;
}
else{
reacId = checkReac[1].id;  
}*/
            
            
            Contact con = new Contact();
            Id professionalRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Eye_Care_Professional').getRecordTypeId();
            con.FirstName = 'Eye';
            con.LastName = 'Doc';
            con.AccountId = acc1.Id;
            con.Doctor_Type__c = 'M - VSP Member Doctor';
            con.Vision_Care_End_Date__c = null;
            con.Vision_Care_Effective_Date__c =  System.today() - 3;
            con.Degree__c = 'OD';
            con.NPI__c = '1073919239';
            con.Doctor_ID__c = '654654654';
            con.Gender__c = 'Male';
            con.Birthdate__c = Date.newInstance(1990, 07, 31);
            con.RecordTypeId = professionalRecordTypeId;
            con.Phone = '1234445656';
            insert con;
            
            Contact_Role__c cr = new Contact_Role__c();
            cr.Account__c = acc1.Id;
            cr.Contact__c = con.Id;
            cr.Type__c = 'Doctor-Employee';
            cr.Start_Date__c = System.today();
            cr.Fee_Code__c = 'NA';
            
            insert cr;
            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'VSP';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            
            insert gt;
            
            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = Date.today().addDays(1);
            
            /*          Network_Relationship__c nr2 = new Network_Relationship__c();
nr2.Contact_Role__c = cr.Id;
nr2.Program_ID__c = gt2.Id;
nr2.Program_Effective_Date__c = Date.today().addDays(1);
nr2.Program_End_Date__c = Date.today().addDays(8);*/
            test.starttest();
            insert nr;
            //     insert nr2;
            //test.stoptest();
            
            
            test.stopTest();
        }  
    }///end testSetup
    
    public static testmethod void updateNetRelEndDate() {
        
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
        Network_Relationship__c NetRel = [SELECT Id, Contact_Role__r.Account__r.Id from Network_Relationship__c 
                                          WHERE Contact_Role__r.Account__r.RecordTypeId = :businessRecordTypeId 
                                          AND Contact_Role__r.Account__r.ParentId != NULL 
                                          AND Contact_Role__r.Contact__r.Vision_Care_Effective_Date__c != NULL
                                          AND (Program_End_Date__c >= TODAY OR Program_End_Date__c = null ) LIMIT 1];
        //  Contact_Role__c cr1 = [SELECT Id, End_Date__c from Contact_Role__c WHERE Id = :NetRel.Contact_Role__r.Id]; 
        // cr1.End_Date__c = System.today() + 3;
        // cr1.Total_Doctor_Hours__c = 88;
        NetRel.Program_End_Date__c = Date.today().addDays(1);
        test.startTest();
        update NetRel;
        test.stopTest();
        Contact_Role__c cr = [SELECT Id, VSP_Network_Provider__c FROM Contact_Role__c];
        system.assertEquals(false, cr.VSP_Network_Provider__c);
    }
    
    public static testmethod void updateNetRelStartDate() {
        
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
        Network_Relationship__c NetRel = [SELECT Id, Contact_Role__r.Account__r.Id from Network_Relationship__c 
                                          WHERE Contact_Role__r.Account__r.RecordTypeId = :businessRecordTypeId 
                                          AND Contact_Role__r.Account__r.ParentId != NULL 
                                          AND Contact_Role__r.Contact__r.Vision_Care_Effective_Date__c != NULL
                                          AND (Program_End_Date__c >= TODAY OR Program_End_Date__c = null ) LIMIT 1];
        //  Contact_Role__c cr1 = [SELECT Id, End_Date__c from Contact_Role__c WHERE Id = :NetRel.Contact_Role__r.Id]; 
        // cr1.End_Date__c = System.today() + 3;
        // cr1.Total_Doctor_Hours__c = 88;
        NetRel.Program_Effective_Date__c = Date.today();
        test.startTest();
        update NetRel;
        test.stopTest();
        Contact_Role__c cr = [SELECT Id, VSP_Network_Provider__c FROM Contact_Role__c];
        system.assertEquals(true, cr.VSP_Network_Provider__c);
    }
    
    public static testmethod void insertNetRelActive() {
        
        Contact_Role__c cr = [SELECT Id FROM Contact_Role__c];
        General_Table__c gt2 = new General_Table__c();
        gt2.Name = 'COSTA';
        gt2.Table__c = 'PRSP';
        gt2.Status__c = 'Active';
        
        insert gt2;
        
        Network_Relationship__c nr2 = new Network_Relationship__c();
        nr2.Contact_Role__c = cr.Id;
        nr2.Program_ID__c = gt2.Id;
        nr2.Program_Effective_Date__c = Date.today();
        nr2.Program_End_Date__c = Date.today().addDays(7);
        test.startTest();
        insert nr2;
        test.stopTest();
        cr = [SELECT Id, VSP_Network_Provider__c FROM Contact_Role__c];
        system.assertEquals(true, cr.VSP_Network_Provider__c);
        
      //  delete nr2;
     //   cr = [SELECT Id, VSP_Network_Provider__c FROM Contact_Role__c];
      //  system.assertEquals(false, cr.VSP_Network_Provider__c);
    }
    
    public static testmethod void deleteNetRel() {
         Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
               Network_Relationship__c NetRel = [SELECT Id, Contact_Role__r.Account__r.Id from Network_Relationship__c 
                                          WHERE Contact_Role__r.Account__r.RecordTypeId = :businessRecordTypeId 
                                          AND Contact_Role__r.Account__r.ParentId != NULL 
                                          AND Contact_Role__r.Contact__r.Vision_Care_Effective_Date__c != NULL
                                          AND (Program_End_Date__c >= TODAY OR Program_End_Date__c = null ) LIMIT 1];
       Contact_Role__c cr = [SELECT Id, VSP_Network_Provider__c FROM Contact_Role__c]; 
        cr.VSP_Network_Provider__c = True;
        update cr;
        
        test.startTest();
        delete NetRel;
        test.stopTest();
        cr = [SELECT Id, VSP_Network_Provider__c FROM Contact_Role__c];
        system.assertEquals(false, cr.VSP_Network_Provider__c);
    }
}