src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>For Practice and Business accounts so that the data can be populated for use in premier tier calculation.
Population on Business account will be manual or through data loader.</description>
        <inlineHelpText>Identifies the location&apos;s relationship with VSP for Premier Tiering</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Company__c</fullName>
        <label>Parent Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AEHG- Acuity Eyecare Holding Group</fullName>
                </value>
                <value>
                    <fullName>CLRK - Clarkson Eyecare Location</fullName>
                </value>
                <value>
                    <fullName>COHN - Cohen&apos;s Fashion Optical</fullName>
                </value>
                <value>
                    <fullName>COST - Costco Location</fullName>
                </value>
                <value>
                    <fullName>CVS - CVS Location</fullName>
                </value>
                <value>
                    <fullName>ECCA - ECCA or Visionworks Location</fullName>
                </value>
                <value>
                    <fullName>ESP - Eyecare Service Partners</fullName>
                </value>
                <value>
                    <fullName>FEGV - For Eyes Grand Vision</fullName>
                </value>
                <value>
                    <fullName>GRRA - Grand Rapids Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>INTL - International Eyecare Center Location</fullName>
                </value>
                <value>
                    <fullName>JVNTR - Joint Ventures</fullName>
                </value>
                <value>
                    <fullName>MEDR - MyEyeDr. Location</fullName>
                </value>
                <value>
                    <fullName>OCNB - Near-site Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>OCSI - Onsite Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>OPTX - Optyx Location</fullName>
                </value>
                <value>
                    <fullName>PERL - Pearle Vision Location</fullName>
                </value>
                <value>
                    <fullName>POP - Pop-Up Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>PRIT - Pritchett Eye Care Location</fullName>
                </value>
                <value>
                    <fullName>RXOP - Rx Optical Location</fullName>
                </value>
                <value>
                    <fullName>SHOP - Shopko Location</fullName>
                </value>
                <value>
                    <fullName>TECP - Total Eyecare Partners</fullName>
                </value>
                <value>
                    <fullName>TOTV - Total Vision Inc</fullName>
                </value>
                <value>
                    <fullName>VNTR - VSP Ventures</fullName>
                </value>
                <value>
                    <fullName>WALM - Walmart Location</fullName>
                </value>
                <value>
                    <fullName>WVIS - Wisconsin Vision Location</fullName>
                </value>
                <value>
                    <fullName>OCCV - CVS Location, VSP</fullName>
                    <isActive>false</isActive>
                    <label>OCCV - CVS Location, VSP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Category__c</fullName>
        <label>Provider Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AOP - Approved OON Provider</fullName>
                </value>
                <value>
                    <fullName>CAT2 - Non-Standard Ownership Model</fullName>
                </value>
                <value>
                    <fullName>CNTRC - Contract Provider</fullName>
                </value>
                <value>
                    <fullName>OFPCS - Pearle Vision Corp Sublease Holder</fullName>
                </value>
                <value>
                    <fullName>OFPLS - Pearle Vision L.O Sublease Holder</fullName>
                </value>
                <value>
                    <fullName>PEARL - License Operator Pearle Vision</fullName>
                </value>
                <value>
                    <fullName>PVCO - Corp Managed Pearle Vision</fullName>
                </value>
                <value>
                    <fullName>RETL - VSP Retail</fullName>
                </value>
                <value>
                    <fullName>SCHLS - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>VNTR - VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is account in good standing with Vision Care.</description>
        <inlineHelpText>Is account in good standing with Vision Care.</inlineHelpText>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/busContractTypeOneTimeCalBatch_Test.cls
@isTest public class busContractTypeOneTimeCalBatch_Test {
    
    private static Id businessRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
    private static Id practiceRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();

    public static testmethod void testMethod1(){

        Exception_Handler_Email__c email = new Exception_Handler_Email__c();
        email.Name = 'test@test.net';
        insert email;

        Account acc = new Account();
        acc.Name = 'Practice Test Account';
        acc.Vision_Care_Good_Standing__c = true;
        acc.recordTypeId = practiceRecordTypeID;
        insert acc;

        Account a = new Account();
        a.Name = 'Testing Account';
        a.Location_Type__c = 'X - Client Authorized Location (GAP)';
        a.Vision_Care_Good_Standing__c = true;
        a.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
        a.Parent_Company__c = 'PERL - Pearle Vision Location';
        a.recordTypeID = businessRecordTypeID;
        a.ParentId = acc.id;
        a.Vision_Care_Effective_Date__c = System.today().addDays(-1);
        a.Vision_Care_End_Date__c = System.today().addMonths(1);
        insert a;

        //System.debug(a);

        a.Contract_Type__c = null;
        update a;

        Test.startTest();
        BusContractTypeOneTimeCalBatch job = new BusContractTypeOneTimeCalBatch();
        Id jobId = Database.executeBatch(job);
        Test.stopTest();

        Account a1 = [Select id, Contract_Type__c from Account where Name = 'Testing Account'];
        System.assertEquals(a1.Contract_Type__c, 'GAP');
    }

    public static testmethod void testMethod2(){

        Exception_Handler_Email__c email = new Exception_Handler_Email__c();
        email.Name = 'test@test.net';
        insert email;

        Account acc = new Account();
        acc.Name = 'Practice Test Account';
        acc.Vision_Care_Good_Standing__c = true;
        acc.recordTypeId = practiceRecordTypeID;
        insert acc;

        Account a = new Account();
        a.Name = 'Testing Account';
        a.Location_Type__c = 'X - Client Authorized Location (GAP)';
        a.Vision_Care_Good_Standing__c = true;
        a.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
        a.Parent_Company__c = 'PERL - Pearle Vision Location';
        a.recordTypeID = businessRecordTypeID;
        a.ParentId = acc.id;
        a.Vision_Care_Effective_Date__c = System.today().addDays(-1);
        a.Vision_Care_End_Date__c = System.today().addMonths(1);
        insert a;

        //System.debug(a);

        acc.Vision_Care_Good_Standing__c = false;
        update acc;

        Test.startTest();
        BusContractTypeOneTimeCalBatch job = new BusContractTypeOneTimeCalBatch();
        Id jobId = Database.executeBatch(job);
        Test.stopTest();

        Account a1 = [Select id, Contract_Type__c from Account where Name = 'Testing Account'];
        System.assertEquals(a1.Contract_Type__c, null);
    }

    public static testmethod void testMethod3(){

        Exception_Handler_Email__c email = new Exception_Handler_Email__c();
        email.Name = 'test@test.net';
        insert email;

        Account acc = new Account();
        acc.Name = 'Practice Test Account';
        acc.Vision_Care_Good_Standing__c = true;
        acc.recordTypeId = practiceRecordTypeID;
        insert acc;

        Account a = new Account();
        a.Name = 'Testing Account';
        a.Location_Type__c = 'X - Client Authorized Location (GAP)';
        a.Vision_Care_Good_Standing__c = true;
        a.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
        a.Parent_Company__c = 'PERL - Pearle Vision Location';
        a.recordTypeID = businessRecordTypeID;
        a.ParentId = acc.id;
        a.Vision_Care_Effective_Date__c = System.today().addDays(-1);
        a.Vision_Care_End_Date__c = System.today().addMonths(1);
        insert a;

        //System.debug(a);

        a.Vision_Care_Good_Standing__c = false;
        update a;

        Test.startTest();
        BusContractTypeOneTimeCalBatch job = new BusContractTypeOneTimeCalBatch();
        Id jobId = Database.executeBatch(job);
        Test.stopTest();

        Account a1 = [Select id, Contract_Type__c from Account where Name = 'Testing Account'];
        System.assertEquals(a1.Contract_Type__c, null);
    }
}