src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>For Practice and Business accounts so that the data can be populated for use in premier tier calculation.
Population on Business account will be manual or through data loader.</description>
        <inlineHelpText>Identifies the location&apos;s relationship with VSP for Premier Tiering</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exclusive_VSP_Patient_Offers__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check when none of the qualifying business accounts have NODIS - Opts out of discounts for Participation Exclusion</description>
        <label>Exclusive VSP Patient Offers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Fitting_and_Adjustments__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Free Fitting and Adjustments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Global_Rewards_Group__c.object
<CustomObject>
    <description>Parent object in a relationship that groups multiple Business/Practice Accounts under one Global Rewards Program (child object is Global Rewards Group Relationship)</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>Visionworks</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exclusive_VSP_Patient_Offers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclusive VSP Patient Offers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Fitting_and_Adjustments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Free Fitting and Adjustments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( OR( Start_Date__c = TODAY() , AND( Start_Date__c &lt; TODAY() , OR( End_Date__c &gt;= TODAY() , ISBLANK( End_Date__c ) ) ) ) , &quot;Active&quot;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Global Rewards Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Rewards Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Rewards_Group_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Account__c</fullName>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Global_Rewards_Group__c</fullName>
        <label>Global Rewards Group</label>
        <referenceTo>Global_Rewards_Group__c</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF((Start_Date__c &lt;= TODAY() &amp;&amp; (ISBLANK(End_Date__c) ||  End_Date__c &gt;= TODAY())), &apos;Active&apos;, 
IF((Start_Date__c &gt; Today()), &apos;Future&apos;, &apos;Inactive&apos;))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group Relationship</label>
    <nameField>
        <displayFormat>PREMIER-{0000}</displayFormat>
        <label>Global Rewards Group Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Rewards Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR34_FFaaNodisGrgHelper.cls
public class VSPR34_FFaaNodisGrgHelper {

    private static final Id businessRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();

    @InvocableMethod(label='Update GRG Exclusive VSP and Free Fitting Indicator' description='Updating the Practice Exclusive VSP Patient Offers and Free Fitting and Adjustments Indicator based on the Business Account corresponding values')
    public static void grgFFaaNodisUpdate(List<Id> busAccId){
        List<Global_Rewards_Group_Relationship__c> grgrList = [Select id, Child_Account__c, Global_Rewards_Group__c from Global_Rewards_Group_Relationship__c where Child_Account__c in :busAccId and Status__c = 'Active'];
        Set<Id> grgIdSet = new Set<Id>();

        for(Global_Rewards_Group_Relationship__c grgr: grgrList){
            grgIdSet.add(grgr.Global_Rewards_Group__c);
        }
        
        List<Global_Rewards_Group_Relationship__c> allGrgrList = [Select id, Child_Account__c, Global_Rewards_Group__c from Global_Rewards_Group_Relationship__c where Global_Rewards_Group__c in :grgIdSet and Child_Account__r.recordTypeId = :businessRecordTypeID and Status__c = 'Active'];
        Map<Id, Set<Id>> grgGrgrIdMap = new Map<Id, Set<Id>>();
        Map<Id, Id> grgrBusAccIdMap = new Map<Id, Id>();

        for(Global_Rewards_Group_Relationship__c grgr: allGrgrList){
            if(!grgGrgrIdMap.containsKey(grgr.Global_Rewards_Group__c)){
                grgGrgrIdMap.put(grgr.Global_Rewards_Group__c, new Set<iD>{grgr.Id});
            }else{
                Set<Id> s = new Set<Id>(grgGrgrIdMap.get(grgr.Global_Rewards_Group__c));
                s.add(grgr.Id);
                grgGrgrIdMap.put(grgr.Global_Rewards_Group__c, s);
            }
            grgrBusAccIdMap.put(grgr.Id, grgr.Child_Account__c);
        }

        List<Account> busAccList = [Select id, Free_Fitting_and_Adjustments__c, Exclusive_VSP_Patient_Offers__c from Account where recordTypeId = :businessRecordTypeID and id in :grgrBusAccIdMap.values() and VC__c = true and (Free_Fitting_and_Adjustments__c = true or Exclusive_VSP_Patient_Offers__c = false)];

        Set<Id> busAccFFaaSet = new Set<Id>();
        Set<Id> busAccNodisSet = new Set<Id>(); 

        for(Account a: busAccList){
            if(!a.Exclusive_VSP_Patient_Offers__c){
                busAccNodisSet.add(a.Id);
            }
            if(a.Free_Fitting_and_Adjustments__c){
                busAccFFaaSet.add(a.Id);
            }
        }

        List<Global_Rewards_Group__c> grgListToUpdate = new List<Global_Rewards_Group__c>();

        for (Id i: grgIdSet) {
            Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
            grg.Id = i;
            /*Boolean check = false;
            Boolean bool = false;*/
            Boolean ffaa = false;
            Boolean nodis = false;
            for(Id grgrI: grgGrgrIdMap.get(i)){
                if(grgrBusAccIdMap.containsKey(grgrI)){
                    if(ffaa && nodis){
                        break;
                    }else{
                        if(busAccNodisSet.contains(grgrBusAccIdMap.get(grgrI))){
                            if(!nodis){
                                nodis = true;
                                //bool = true;
                            }
                        }
                        if(busAccFFaaSet.contains(grgrBusAccIdMap.get(grgrI))){
                            if(!ffaa){
                                ffaa = true;
                                //bool = true;
                            }
                        }
                    }
                }
            }
            
            if(nodis){
                grg.Exclusive_VSP_Patient_Offers__c = false;
            }else{
                grg.Exclusive_VSP_Patient_Offers__c = true;
            }

            if(!ffaa){
                grg.Free_Fitting_and_Adjustments__c = false;
            }else{
                grg.Free_Fitting_and_Adjustments__c = true;
            }
            
            grgListToUpdate.add(grg);

        }

        if(grgListToUpdate.size()>0){
            update grgListToUpdate;
        }
    }

    /*public static void test(List<Id> busAccId){
        List<Global_Rewards_Group_Relationship__c> grgrList = [Select id, Child_Account__c, Global_Rewards_Group__c from Global_Rewards_Group_Relationship__c where Child_Account__c in :busAccId and Status__c = 'Active'];
        Set<Id> grgIdSet = new Set<Id>();
        List<Global_Rewards_Group__c> grgToUpdateList = new List<Global_Rewards_Group__c>();
        Map<Id, Global_Rewards_Group__c> grgMap = new Map<Id, Global_Rewards_Group__c>();

        for(Global_Rewards_Group_Relationship__c grgr: grgrList){
            grgMap.put(grgr.Global_Rewards_Group__c, new Global_Rewards_Group__c(Id = grgr.Global_Rewards_Group__c, Exclusive_VSP_Patient_Offers__c = true, Free_Fitting_and_Adjustments__c = false));
            //grgIdSet.add(grgr.Global_Rewards_Group__c);
        }

        AggregateResult[] busAccNODISCount =   [SELECT Global_Rewards_Group__c, Count(Id) Total 
                                                    FROM Global_Rewards_Group_Relationship__c 
                                                    WHERE Global_Rewards_Group__c IN :grgMap.keySet() AND 
                                                    Status__c = 'Active' AND
                                                    Child_Account__r.VC__c = True AND
                                                    //Child_Account__r.Status__c = 'A' AND
                                                    //Child_Account__r.Vision_Care_Effective_Date__c <= TODAY AND
                                                    //(Child_Account__r.Vision_Care_End_Date__c >= TODAY OR Child_Account__r.Vision_Care_End_Date__c = null) AND
                                                    Child_Account__r.recordTypeId = :businessRecordTypeID AND 
                                                    //Child_Account__r.Contract_Type__c != NULL AND 
                                                    Child_Account__r.Exclusive_VSP_Patient_Offers__c = false  
                                                    GROUP BY Global_Rewards_Group__c];

        AggregateResult[] busAccFreeFittingCount =  [SELECT Global_Rewards_Group__c, Count(Id) Total 
                                                         FROM Global_Rewards_Group_Relationship__c 
                                                         WHERE Global_Rewards_Group__c IN :grgMap.keySet() AND Status__c = 'Active' AND
                                                         Child_Account__r.VC__c = True AND
                                                         //Child_Account__r.Status__c = 'A' AND
                                                         // Child_Account__r.Vision_Care_Effective_Date__c <= TODAY AND
                                                         // (Child_Account__r.Vision_Care_End_Date__c >= TODAY OR Child_Account__r.Vision_Care_End_Date__c = null) AND
                                                         Child_Account__r.RecordTypeId = :businessRecordTypeID AND 
                                                         Child_Account__r.Free_Fitting_and_Adjustments__c = true
                                                         Group By Global_Rewards_Group__c];

        for(Global_Rewards_Group__c grg: grgMap.values()){
            for(AggregateResult ag: busAccNODISCount){
                if((Id)ag.get('Global_Rewards_Group__c') == grg.Id){
                    grg.Exclusive_VSP_Patient_Offers__c = false;
                }
            }
            for(AggregateResult ag: busAccFreeFittingCount){
                if((Id)ag.get('Global_Rewards_Group__c') == grg.Id){
                    grg.Free_Fitting_and_Adjustments__c = true;
                }
            }
            grgToUpdateList.add(grg);
        }

        if(grgToUpdateList.size()>0){
            update grgToUpdateList;
        }
    }*/
}