src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Caller_Intent__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Caller Intent</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Main consumer Id field. All other collection fields will pipe to this field. All logic will be based upon this field for consumer Id.</inlineHelpText>
        <label>Consumer ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ContactId</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MemberPlan</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PersonAccount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (PersonAccount)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CC_Portal__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CC Portal</label>
</CustomObject>

src/objects/Consumer_Search_Web_Service__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Consumer_Search_Web_Service__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Consumer Search Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Consumer Search Web Service</label>
</CustomObject>

src/objects/ConsumerSeachResults__c.object
<CustomObject>
    <description>Used to store results from ConsumerdB so they can be displayed and sorted using Lightning dtaaTable.  After CreateCase is called- need to delete these records.</description>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>COnsumer Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>ConsumerSeachResults</label>
    <nameField>
        <displayFormat>CS-{000}</displayFormat>
        <label>ConsumerSeachResults Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ConsumerSeachResults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Consumer_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Consumer ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/VspOauthToken__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Access Token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>expires_in__c</fullName>
        <label>Expires In</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>granted_at__c</fullName>
        <defaultValue>$System.OriginDateTime</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Granted At</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>tokenId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Token Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>VspOauthToken</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VspOauthToken Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VspOauthTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR2_ConsumerSearch_Test.cls
@isTest
public class VSPR2_ConsumerSearch_Test {
    @isTest
    public static void testConsumerSearch(){
     
        //create Person Account
        Id paId = testdatafactory.createPersonAccount('personAccount');
    	//    Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        //Need to create Custom Setting so that VSPR16_GetConsumerID.getConsumerID2 doesnt error
        DVIWebService__c dviCustSetting = testDataFactory.setDVISettings();
        Consumer_Search_Web_Service__c CSCustSetting =testDataFactory.setCSSettings();
        CC_Portal__c ccPortalSettings = testDataFactory.setCCPortalSettings();
       
    	/*    VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok;*/  
        
        case caseobj = new case(); 
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Vision Benefits').getRecordTypeId();
       
        caseobj.recordtypeId = rtId;
           
        insert caseobj; 
        
        consumerseachresults__c csr = new consumerseachresults__c();
        csr.City__c = 'Ranch Cordova';
        insert csr; 
        
        Caller_Intent__c ci = new Caller_Intent__c();
        ci.Name = 'Test';
        ci.Code__c = 'B9902'; 
        ci.Intent_Text__c = 'IntentText';
        insert ci;
      
        Test.startTest();
        Test.setCurrentPageReference(new PageReference('VSPR2_ConsumerSearch.VSPR2_ConsumerSearch'));      
         
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
   
        VSPR2_ConsumerSearch cs = new VSPR2_ConsumerSearch(sc);
        cs.reset();
      
        cs.firstname='ABCDEF';
        cs.lastName='GHIJKL';
        cs.callername='test';
        cs.calltype = 'Member';
        cs.midname='';
        cs.remdob = false;
        cs.activeOnly = false;
        cs.include = true;
        cs.primaryMemberConsumerID = '';
        cs.callerintent = 'B9902';
        cs.ConsumerId = '5'; 
        cs.dob = '03/08/1901';
        cs.classId = '0100';
        cs.reason = 'Benefits';
        cs.reasondetail = 'Benefits detail';
        cs.ciscoContactId = '4';
        cs.ANI = '2';
        cs.DNIS = '1112223333';
        cs.policyid = '4';
        cs.channel = 'phone';
        cs.CEP = '2223334444';
        cs.custBody = 'body';
        
        cs.setparams();
        cs.storeIVRparameters();
        cs.APIsearchRecords();
        cs.togglesort();
        cs.createcase();  //This creates case from JSON
        
        cs.caseobj.PersonAccount__c = paId;      
        cs.createcase();  //This creates case from Person Account
        
        cs.setparams(); 
        cs.getfirstname();
        cs.getlastname();         
        cs.getrelation();         
        cs.getcontactId(); 
        cs.getbirthdate();
        cs.getasofdate();
        cs.getcity();
        cs.getemail();
        cs.getlast4();  
        cs.getlastname();
        cs.getfirstname();
        cs.getrelation();
        cs.getmidname();
        cs.getclientid();
        cs.getinclude();
        cs.getremdob();
        cs.getdob();
        cs.getcname();
        cs.getclassification();
        cs.getphone();
        cs.getactiveOnly();
        cs.getQ();
        cs.getrefresh();
        // gets memberId (capital I)
        cs.get();
        //
        cs.getauth();
        cs.getconsumerId();
        cs.getauthenticated();
        cs.getcallername();
        cs.getsubject();
        cs.getcallerintent();
        cs.getstate();
        cs.gettocase();
        cs.getIVRCalltype();
        cs.getcalltype();
        cs.getConsumers();
        cs.setConsumerID();
        cs.getmemberIds();
        cs.getconsumerids();
        cs.getsortfield(); 
        cs.getauths();
        cs.getnames();
        cs.getname();
        cs.getcaseid();
        cs.getStates();
        cs.getdebugSoql();
        String result = VSPR2_ConsumerSearch.getCCPURL();
        PageReference result2 = VSPR2_ConsumerSearch.finalReset();
        Test.stopTest();
        
        //Assert that case was created and Person Account and Member Plan
        //Contact field = Consumer_ID__c and on Account = Consumer_ID__pc
        String cid = '999999999';
        List<Account> pList = new List<Account>([SELECT id 
                                                 FROM Account 
                                                 WHERE Consumer_Id__pc=:cId]);
        List<Case> caseList = new List<Case>([SELECT ID, Member_Plan__c, AccountId from Case 
                                                WHERE createddate=TODAY 
                                                AND AccountId =:paId
                                                ]);
        //System.Assertequals(caseList.size(),1);
        
        
       
    }
    // need to mock the page 
  /*  @isTest
    public static void testConsumerSearch_validation(){
             
        //create Person Account
        Id paId = testdatafactory.createPersonAccount('personAccount');
    	//    Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        //Need to create Custom Setting so that VSPR16_GetConsumerID.getConsumerID2 doesnt error
        DVIWebService__c dviCustSetting = testDataFactory.setDVISettings();
        Consumer_Search_Web_Service__c CSCustSetting =testDataFactory.setCSSettings();
        CC_Portal__c ccPortalSettings = testDataFactory.setCCPortalSettings();
        
        
        case caseobj = new case(); 
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Vision Benefits').getRecordTypeId();
       
        caseobj.recordtypeId = rtId;
           
        insert caseobj; 
        
        consumerseachresults__c csr = new consumerseachresults__c();
        csr.City__c = 'Ranch Cordova';
        insert csr; 
        
        Caller_Intent__c ci = new Caller_Intent__c();
        ci.Name = 'Test';
        ci.Code__c = 'B9902'; 
        ci.Intent_Text__c = 'IntentText';
        insert ci;
      
        Test.startTest();
        PageReference page = new PageReference('VSPR2_ConsumerSearch.VSPR2_ConsumerSearch');
        Test.setCurrentPageReference(page);
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
   
        VSPR2_ConsumerSearch cs = new VSPR2_ConsumerSearch(sc);
        cs.dob ='07/28/1983';
        cs.APIsearchRecords();
        List<Apexpages.Message> msgs = ApexPages.getMessages();
    	boolean b = false;
    	for(Apexpages.Message msg:msgs){
            System.debug(msg.getDetail());
            if (msg.getDetail().contains('A user account for this email address already exists')) {
                
            }
       }	
        Test.stopTest();
        
    } */
    
}