src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Retinal_Imaging_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check when 1 or more qualifying business accounts have RTLIM - Retinal Imaging value for Service Offering (s)</description>
        <label>Retinal Imaging Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Global_Rewards_Group__c.object
<CustomObject>
    <description>Parent object in a relationship that groups multiple Business/Practice Accounts under one Global Rewards Program (child object is Global Rewards Group Relationship)</description>
    <fields>
        <fullName>Retinal_Imaging_Indicator_Future__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retinal Imaging Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retinal_Imaging_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retinal Imaging Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( OR( Start_Date__c = TODAY() , AND( Start_Date__c &lt; TODAY() , OR( End_Date__c &gt;= TODAY() , ISBLANK( End_Date__c ) ) ) ) , &quot;Active&quot;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Global Rewards Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Rewards Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Rewards_Group_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Account__c</fullName>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Global_Rewards_Group__c</fullName>
        <label>Global Rewards Group</label>
        <referenceTo>Global_Rewards_Group__c</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF((Start_Date__c &lt;= TODAY() &amp;&amp; (ISBLANK(End_Date__c) ||  End_Date__c &gt;= TODAY())), &apos;Active&apos;, 
IF((Start_Date__c &gt; Today()), &apos;Future&apos;, &apos;Inactive&apos;))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group Relationship</label>
    <nameField>
        <displayFormat>PREMIER-{0000}</displayFormat>
        <label>Global Rewards Group Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Rewards Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR33_RetinalImageGrgHelper.cls
public class VSPR33_RetinalImageGrgHelper {
    
    private static final Id businessRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();

    @InvocableMethod(label='Update GRG Retinal Image Indicator' description='Updating the GRG Retinal Image Indicator based on the Business Account Retinal Indicator value')
    public static void updateGrgIndicator(List<Id> busAccId) {

        List<Global_Rewards_Group_Relationship__c> grgrList = [Select id, Child_Account__c, Global_Rewards_Group__c from Global_Rewards_Group_Relationship__c where Child_Account__c in :busAccId and Status__c = 'Active'];
        Set<Id> grgIdSet = new Set<Id>();

        for(Global_Rewards_Group_Relationship__c grgr: grgrList){
            grgIdSet.add(grgr.Global_Rewards_Group__c);
        }
        
        List<Global_Rewards_Group_Relationship__c> allGrgrList = [Select id, Child_Account__c, Global_Rewards_Group__c from Global_Rewards_Group_Relationship__c where Global_Rewards_Group__c in :grgIdSet and Child_Account__r.recordTypeId = :businessRecordTypeID and Status__c = 'Active'];
        Map<Id, Set<Id>> grgGrgrIdMap = new Map<Id, Set<Id>>();
        Map<Id, Id> grgrBusAccIdMap = new Map<Id, Id>();

        for(Global_Rewards_Group_Relationship__c grgr: allGrgrList){
            if(!grgGrgrIdMap.containsKey(grgr.Global_Rewards_Group__c)){
                grgGrgrIdMap.put(grgr.Global_Rewards_Group__c, new Set<iD>{grgr.Id});
            }else{
                Set<Id> s = new Set<Id>(grgGrgrIdMap.get(grgr.Global_Rewards_Group__c));
                s.add(grgr.Id);
                grgGrgrIdMap.put(grgr.Global_Rewards_Group__c, s);
            }
            grgrBusAccIdMap.put(grgr.Id, grgr.Child_Account__c);
        }

        List<Account> busAccList = [Select id, Retinal_Imaging_Indicator__c from Account where recordTypeId = :businessRecordTypeID and id in :grgrBusAccIdMap.values()];

        Map<Id, Boolean> busAccRetinalMap = new Map<Id, Boolean>();

        for(Account a: busAccList){
            busAccRetinalMap.put(a.Id, a.Retinal_Imaging_Indicator__c);
        }

        List<Global_Rewards_Group__c> grgListToUpdate = new List<Global_Rewards_Group__c>();
        Map<Id, Boolean> grgRetinalMap = new Map<Id, Boolean>();

        for (Id i: grgIdSet) {
            Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
            grg.Id = i;
            Boolean check = false;
            for(Id grgrI: grgGrgrIdMap.get(i)){
                if(grgrBusAccIdMap.containsKey(grgrI)){
                    if(busAccRetinalMap.containsKey(grgrBusAccIdMap.get(grgrI))){
                        if(busAccRetinalMap.get(grgrBusAccIdMap.get(grgrI)) && /*count == 0*/ !check){ //test the break statement with multiple grgr and account combinations.
                            check = true;
                            break;
                        }
                    }
                }
            }
            if(check){
                grg.Retinal_Imaging_Indicator_Future__c = true;
                grgListToUpdate.add(grg);
            }else{
                //Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
                //grg.Id = i;
                grg.Retinal_Imaging_Indicator_Future__c = false;
                grgListToUpdate.add(grg);
            }
        }

        if(grgListToUpdate.size()>0){
            update grgListToUpdate;
        }
    }
}