src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Exclusive_VSP_Patient_Offers__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check when none of the qualifying business accounts have NODIS - Opts out of discounts for Participation Exclusion</description>
        <label>Exclusive VSP Patient Offers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Fitting_and_Adjustments__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Free Fitting and Adjustments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Participation_Exclusions__c</fullName>
        <label>Participation Exclusions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ADMCD – Opts out of Medicaid All Doctors</fullName>
                    <label>ADMCD – Opts out of Medicaid All Doctor</label>
                </value>
                <value>
                    <fullName>NODIS – Opts out of discounts</fullName>
                </value>
                <value>
                    <fullName>NOMCR – Opts out of Medicare</fullName>
                </value>
                <value>
                    <fullName>NOCNT – Opts out of providing contacts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Global_Rewards_Group__c.object
<CustomObject>
    <description>Parent object in a relationship that groups multiple Business/Practice Accounts under one Global Rewards Program (child object is Global Rewards Group Relationship)</description>
    <fields>
        <fullName>Exclusive_VSP_Patient_Offers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclusive VSP Patient Offers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Free_Fitting_and_Adjustments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Free Fitting and Adjustments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( OR( Start_Date__c = TODAY() , AND( Start_Date__c &lt; TODAY() , OR( End_Date__c &gt;= TODAY() , ISBLANK( End_Date__c ) ) ) ) , &quot;Active&quot;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Global Rewards Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Rewards Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Rewards_Group_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Account__c</fullName>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Global_Rewards_Group__c</fullName>
        <label>Global Rewards Group</label>
        <referenceTo>Global_Rewards_Group__c</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the child record was added to the Parent Roll up account.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF((Start_Date__c &lt;= TODAY() &amp;&amp; (ISBLANK(End_Date__c) ||  End_Date__c &gt;= TODAY())), &apos;Active&apos;, 
IF((Start_Date__c &gt; Today()), &apos;Future&apos;, &apos;Inactive&apos;))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group Relationship</label>
    <nameField>
        <displayFormat>PREMIER-{0000}</displayFormat>
        <label>Global Rewards Group Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Rewards Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR34_FfaaNodis_Test.cls
@isTest
public class VSPR34_FfaaNodis_Test {
    private static final Id businessRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
    private static final Id practiceRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
    private static final Id contractTypeGrgRecordTypeID = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Contract Type').getRecordTypeId();
    private static final Date todayDate = System.today();

    @IsTest
    static void testmethod1(){
        
        Account p1 = new Account();
        p1.Name = 'Practice Test Account';
        p1.Vision_Care_Effective_Date__c = todayDate;
        p1.recordTypeId = practiceRecordTypeID;
        insert p1;

        /*Account pracAcc = [Select id, VC__c from Account where recordTypeId = :practiceRecordTypeID and id = :p1.Id];
        System.assertEquals(pracAcc.VC__c, true);*/

        Account b1 = new Account();
        b1.Name = 'Business Test Account 1';
        b1.Vision_Care_Effective_Date__c = todayDate;
        b1.Vision_Care_End_Date__c = todayDate.addYears(1);
        b1.ParentId = p1.Id;
        b1.recordTypeId = businessRecordTypeID;
        b1.Participation_Exclusions__c = 'NOFFAA – Opts out of free fittings and adjustments';
        //test.startTest();   
        insert b1;
        
        Account baRec = [SELECT Id, Name, Participation_Exclusions__c, VC__c, Free_Fitting_and_Adjustments__c 
                         FROM Account 
                         WHERE Id =: b1.Id];
        
        //test.stopTest();
        
        //system.assertEquals(null, baRec.Participation_Exclusions__c);
        system.assertEquals(true, baRec.VC__c);
        system.assertEquals(false, baRec.Free_Fitting_and_Adjustments__c);

        Account b2 = new Account();
        b2.Name = 'Business Test Account 2';
        b2.Vision_Care_Effective_Date__c = todayDate;
        b2.Vision_Care_End_Date__c = todayDate.addYears(1);
        b2.ParentId = p1.Id;
        b2.recordTypeId = businessRecordTypeID;
        b1.Participation_Exclusions__c = 'NOFFAA – Opts out of free fittings and adjustments';
        //test.startTest();   
        insert b2;

        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = contractTypeGrgRecordTypeID;
        insert grg;

        List<Global_Rewards_Group_Relationship__c> grgrList = new List<Global_Rewards_Group_Relationship__c>();

        Global_Rewards_Group_Relationship__c grgr1 = new Global_Rewards_Group_Relationship__c();
        grgr1.Start_Date__c = todayDate;
        grgr1.Global_Rewards_Group__c = grg.Id;
        grgr1.Child_Account__c = b1.Id;
        grgrList.add(grgr1);

        Global_Rewards_Group_Relationship__c grgr2 = new Global_Rewards_Group_Relationship__c();
        grgr2.Start_Date__c = todayDate;
        grgr2.Global_Rewards_Group__c = grg.Id;
        grgr2.Child_Account__c = b2.Id;
        grgrList.add(grgr2);
        
        insert grgrList;

        //System.debug(grgrList);
        /*List<Global_Rewards_Group_Relationship__c> grgrList1 = [Select id, Status__c from Global_Rewards_Group_Relationship__c];
        System.debug(grgrList1);*/

        b2.Participation_Exclusions__c = 'NODIS – Opts out of discounts';
        update b2;

        Account b3 = [SELECT Id, Name, Exclusive_VSP_Patient_Offers__c, VC__c, Free_Fitting_and_Adjustments__c 
                         FROM Account 
                         WHERE Id =: b2.Id];

        system.assertEquals(true, b3.VC__c);
        system.assertEquals(false, b3.Exclusive_VSP_Patient_Offers__c);
        system.assertEquals(false, b3.Free_Fitting_and_Adjustments__c);

        Global_Rewards_Group__c grg1 = [Select id, Exclusive_VSP_Patient_Offers__c, Free_Fitting_and_Adjustments__c from Global_Rewards_Group__c where Id = :grg.Id];
        System.assertEquals(false, grg1.Free_Fitting_and_Adjustments__c);
        System.assertEquals(false, grg1.Exclusive_VSP_Patient_Offers__c);

        
        b1.Participation_Exclusions__c = 'NODIS – Opts out of discounts; NOFFAA – Opts out of free fittings and adjustments';
        update b1;
        

    }

    @IsTest
    static void testmethod2(){
        
        Account p1 = new Account();
        p1.Name = 'Practice Test Account';
        p1.Vision_Care_Effective_Date__c = todayDate.addDays(1);
        p1.recordTypeId = practiceRecordTypeID;
        insert p1;

        /*Account pracAcc = [Select id, VC__c from Account where recordTypeId = :practiceRecordTypeID and id = :p1.Id];
        System.assertEquals(pracAcc.VC__c, true);*/

        Account b1 = new Account();
        b1.Name = 'Business Test Account 1';
        b1.Vision_Care_Effective_Date__c = todayDate;
        b1.Vision_Care_End_Date__c = todayDate.addYears(1);
        b1.ParentId = p1.Id;
        b1.recordTypeId = businessRecordTypeID;
        b1.Participation_Exclusions__c = 'NOFFAA – Opts out of free fittings and adjustments';
        //test.startTest();   
        insert b1;

        p1.Vision_Care_Effective_Date__c = System.today();
        update p1;

        Account b2 = new Account();
        b2.Name = 'Business Test Account 1';
        b2.Vision_Care_Effective_Date__c = todayDate;
        b2.Vision_Care_End_Date__c = todayDate.addYears(1);
        b2.ParentId = p1.Id;
        b2.recordTypeId = businessRecordTypeID;
        b2.Participation_Exclusions__c = 'NODIS – Opts out of discounts';
        //test.startTest();   
        insert b2;

        b1.Participation_Exclusions__c = null;
        update b1;

        b2.Participation_Exclusions__c = null;
        update b2;

        b1.Vision_Care_Effective_Date__c = System.today().addDays(1);
        b2.Vision_Care_Effective_Date__c = System.today().addDays(1);
        update b1;
        update b2;

        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = contractTypeGrgRecordTypeID;
        insert grg;

        List<Global_Rewards_Group_Relationship__c> grgrList = new List<Global_Rewards_Group_Relationship__c>();

        grgrList.add(new Global_Rewards_Group_Relationship__c(Child_Account__c = b1.Id, Start_Date__c = System.today(), Global_Rewards_Group__c = grg.Id));
        grgrList.add(new Global_Rewards_Group_Relationship__c(Child_Account__c = b2.Id, Start_Date__c = System.today(), Global_Rewards_Group__c = grg.Id));
        grgrList.add(new Global_Rewards_Group_Relationship__c(Child_Account__c = p1.Id, Start_Date__c = System.today(), Global_Rewards_Group__c = grg.Id));
        
        insert grgrList;

        /*List<Global_Rewards_Group_Relationship__c> grgrList1 = [Select id, Child_Account__r.recordTypeId, Status__c from Global_Rewards_Group_Relationship__c where Global_Rewards_Group__c = :grg.Id];
        System.debug(grgrList1);*/

        b1.Vision_Care_Effective_Date__c = System.today();
        b2.Vision_Care_Effective_Date__c = System.today();
        update b1;
        update b2;

        List<Account> accList = [Select id, Free_Fitting_and_Adjustments__c, Exclusive_VSP_Patient_Offers__c, VC__c from Account where id = :b1.Id or id = :b2.Id];
        for(Account a: accList){
            //System.debug(a);
            System.assertEquals(true, a.VC__c);
        }

        b1.Participation_Exclusions__c = 'NODIS – Opts out of discounts';
        b1.Free_Fitting_and_Adjustments__c = true;
        update b1;

        Account p2 = [Select id, Free_Fitting_and_Adjustments__c, Exclusive_VSP_Patient_Offers__c, VC__c from Account where id = :p1.Id];
        /*System.assertEquals(true, p2.Free_Fitting_and_Adjustments__c);
        System.assertEquals(false, p2.Exclusive_VSP_Patient_Offers__c);*/
        
    }
}