src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>For Practice and Business accounts so that the data can be populated for use in premier tier calculation.
Population on Business account will be manual or through data loader.</description>
        <inlineHelpText>Identifies the location&apos;s relationship with VSP for Premier Tiering</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Non_VC_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non VC Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Company__c</fullName>
        <label>Parent Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AEHG- Acuity Eyecare Holding Group</fullName>
                </value>
                <value>
                    <fullName>CLRK - Clarkson Eyecare Location</fullName>
                </value>
                <value>
                    <fullName>COHN - Cohen&apos;s Fashion Optical</fullName>
                </value>
                <value>
                    <fullName>COST - Costco Location</fullName>
                </value>
                <value>
                    <fullName>CVS - CVS Location</fullName>
                </value>
                <value>
                    <fullName>ECCA - ECCA or Visionworks Location</fullName>
                </value>
                <value>
                    <fullName>ESP - Eyecare Service Partners</fullName>
                </value>
                <value>
                    <fullName>FEGV - For Eyes Grand Vision</fullName>
                </value>
                <value>
                    <fullName>GRRA - Grand Rapids Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>INTL - International Eyecare Center Location</fullName>
                </value>
                <value>
                    <fullName>JVNTR - Joint Ventures</fullName>
                </value>
                <value>
                    <fullName>MEDR - MyEyeDr. Location</fullName>
                </value>
                <value>
                    <fullName>OCNB - Near-site Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>OCSI - Onsite Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>OPTX - Optyx Location</fullName>
                </value>
                <value>
                    <fullName>PERL - Pearle Vision Location</fullName>
                </value>
                <value>
                    <fullName>POP - Pop-Up Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>PRIT - Pritchett Eye Care Location</fullName>
                </value>
                <value>
                    <fullName>RXOP - Rx Optical Location</fullName>
                </value>
                <value>
                    <fullName>SHOP - Shopko Location</fullName>
                </value>
                <value>
                    <fullName>TECP - Total Eyecare Partners</fullName>
                </value>
                <value>
                    <fullName>TOTV - Total Vision Inc</fullName>
                </value>
                <value>
                    <fullName>VNTR - VSP Ventures</fullName>
                </value>
                <value>
                    <fullName>WALM - Walmart Location</fullName>
                </value>
                <value>
                    <fullName>WVIS - Wisconsin Vision Location</fullName>
                </value>
                <value>
                    <fullName>OCCV - CVS Location, VSP</fullName>
                    <isActive>false</isActive>
                    <label>OCCV - CVS Location, VSP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Category__c</fullName>
        <label>Provider Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AOP - Approved OON Provider</fullName>
                </value>
                <value>
                    <fullName>CAT2 - Non-Standard Ownership Model</fullName>
                </value>
                <value>
                    <fullName>CNTRC - Contract Provider</fullName>
                </value>
                <value>
                    <fullName>OFPCS - Pearle Vision Corp Sublease Holder</fullName>
                </value>
                <value>
                    <fullName>OFPLS - Pearle Vision L.O Sublease Holder</fullName>
                </value>
                <value>
                    <fullName>PEARL - License Operator Pearle Vision</fullName>
                </value>
                <value>
                    <fullName>PVCO - Corp Managed Pearle Vision</fullName>
                </value>
                <value>
                    <fullName>RETL - VSP Retail</fullName>
                </value>
                <value>
                    <fullName>SCHLS - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>VNTR - VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is account in good standing with Vision Care.</description>
        <inlineHelpText>Is account in good standing with Vision Care.</inlineHelpText>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Exception__c</fullName>
        <label>Vision Care Location Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AGT - Agreement Non-Compliance</fullName>
                </value>
                <value>
                    <fullName>CTG - Group Agreement</fullName>
                </value>
                <value>
                    <fullName>DRS - Not all doctors are VSP Providers</fullName>
                </value>
                <value>
                    <fullName>DSP - Does not Dispense Glasses</fullName>
                </value>
                <value>
                    <fullName>FQH - FQHC Center</fullName>
                </value>
                <value>
                    <fullName>HRSA - Office Hours Exception</fullName>
                </value>
                <value>
                    <fullName>IHSC - Indian Health Clinic</fullName>
                </value>
                <value>
                    <fullName>SITE - On-site Clinic</fullName>
                </value>
                <value>
                    <fullName>COFR - Does not Maintain 200 Frames</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Practice_Exception__c</fullName>
        <label>Vision Care Practice Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AOFF - Non-VSP Location</fullName>
                </value>
                <value>
                    <fullName>EFTX - No EFT</fullName>
                </value>
                <value>
                    <fullName>OFF - Does not own Dispensary</fullName>
                </value>
                <value>
                    <fullName>POWN - Non-Doctor Ownership</fullName>
                </value>
                <value>
                    <fullName>EQOW - Does not meet Equipment or Ownership Requirements</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BusContractTypeOneTimeCalBatch.cls
global class BusContractTypeOneTimeCalBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    private static final Id businessRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
    private static final Id practiceRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
    private static final Date todayDate = System.today();
    private static List<String> exceptionList = new List<String>();
    private static final String query = 'Select Id, Non_VC_Exception__c,	Parent_Company__c, Vision_Care_Good_Standing__c, Vision_Care_Effective_Date__c, Vision_Care_End_Date__c, Location_Type__c, Provider_Category__c, Vision_Care_Location_Exception__c, ParentId, recordTypeId from Account where recordTypeId = \'' + businessRecordTypeID + '\' and ParentId != null and Vision_Care_Effective_Date__c != null';
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope){

        List<Account> busAccToUpdate = new List<Account>();
        Set<Id> pracIdSet = new Set<Id>();
        Map<Id, String> practiceExceptionMap = new Map<Id, String>();
        
        for(Account a: scope){
            pracIdSet.add(a.ParentId);
        }

        List<Account> practAccountList = [Select id, Vision_Care_Practice_Exception__c from Account where recordTypeID = :practiceRecordTypeID and id in :pracIdSet and Vision_Care_Good_Standing__c = true];

        for(Account a: practAccountList){
            practiceExceptionMap.put(a.Id, a.Vision_Care_Practice_Exception__c);
        }

        for(Account a: scope){
            if (!a.Vision_Care_Good_Standing__c) {
                a.Contract_Type__c = null;
            }
            else if(practiceExceptionMap.containsKey(a.ParentId)){
                VSPR31_BusAccContractTypeCalculation cal = new VSPR31_BusAccContractTypeCalculation();
                cal.calculator(a, practiceExceptionMap.get(a.Id));
            }else {
                a.Contract_Type__c = null;
            }
            busAccToUpdate.add(a);
        }

        if(busAccToUpdate.size()>0){
            Database.SaveResult[] SaveResultList = Database.update(busAccToUpdate, false);

            for(integer i =0; i<busAccToUpdate.size();i++){
                String msg='';
                if(!SaveResultList[i].isSuccess()){
                    msg += busAccToUpdate.get(i).id + '\n'+'Error: "';
                    for(Database.Error err: SaveResultList[i].getErrors()){
                        msg += err.getmessage()+'"\n\n';
                    } 
                }
                if(msg!= ''){
                    exceptionList.add(msg);
                }
            }
        }

    }

    global void finish(Database.BatchableContext BC){

        if(!exceptionList.isEmpty() || Test.isRunningTest()){
            List<Exception_handler_Email__c> toEmailLst = Exception_handler_Email__c.getall().values();
            
            if(!toEmailLst.isEmpty()){
                String[] toAddresses = new String[]{};
                for(Exception_Handler_Email__c obj:[select Name from Exception_Handler_Email__c]){
                    toAddresses.add(obj.Name);
                }
                
                Messaging.reserveSingleEmailCapacity(2);
                
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                
                mail.setToAddresses(toAddresses);
                
                mail.setSenderDisplayName('Salesforce Support');
                
                mail.setSubject('Business Account Contract Type One Time Calculation Batch');
                
                mail.setBccSender(false);
                
                mail.setUseSignature(false);
                
                // Specify the text content of the email.
                mail.setPlainTextBody('Number of records failed = ' + exceptionList.size());
                
                mail.setHtmlBody('Number of records failed = ' + exceptionList.size() + '<br><br>' + exceptionList + '<br><br>');
                
                // Send the email you have created.
                if(!Test.isRunningTest()){
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                }
            }
        }

    }
}