src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ConsumerID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <inlineHelpText>The relevant category for the Issue or Request.</inlineHelpText>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account/Contact Maintenance</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Credentialing/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Main client Id field. All other collection fields will pipe to this field. All logic will be based upon this field for client Id.</inlineHelpText>
        <label>Client Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Main consumer Id field. All other collection fields will pipe to this field. All logic will be based upon this field for consumer Id.</inlineHelpText>
        <label>Consumer ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ContactId</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MemberPlan</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PersonAccount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (PersonAccount)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryMemberConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PrimaryMemberConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CallerType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2020Source Assistance</fullName>
                </value>
                <value>
                    <fullName>AOB/OON Provider</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Claim Payment</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Claims Adjustment</fullName>
                </value>
                <value>
                    <fullName>Client Benefits</fullName>
                </value>
                <value>
                    <fullName>Client Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Client Exceptions</fullName>
                </value>
                <value>
                    <fullName>Client Website Assistance</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Delays</fullName>
                </value>
                <value>
                    <fullName>Doctor Referral</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Eyefinity Assistance</fullName>
                </value>
                <value>
                    <fullName>Frame</fullName>
                </value>
                <value>
                    <fullName>Injury</fullName>
                </value>
                <value>
                    <fullName>Language Lines / Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Member Authorization</fullName>
                </value>
                <value>
                    <fullName>Member Benefits</fullName>
                </value>
                <value>
                    <fullName>Member Caller</fullName>
                </value>
                <value>
                    <fullName>Member Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Member Experience</fullName>
                </value>
                <value>
                    <fullName>Member Website Assistance</fullName>
                </value>
                <value>
                    <fullName>OON Caller</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CC_Portal__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CC Portal</label>
</CustomObject>

src/objects/Consumer_Search_Web_Service__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Consumer_Search_Web_Service__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Consumer Search Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Consumer Search Web Service</label>
</CustomObject>

src/objects/MemberPlan.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Consumer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Id</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>primaryMemberConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Member Consumer Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VspOauthToken__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Access Token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>expires_in__c</fullName>
        <label>Expires In</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>granted_at__c</fullName>
        <defaultValue>$System.OriginDateTime</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Granted At</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>tokenId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Token Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>VspOauthToken</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VspOauthToken Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VspOauthTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR2_GetPropensityScores_Test.cls
@isTest
public class VSPR2_GetPropensityScores_Test {
    @isTest 
    public static void getScoresWithCallout(){  
        List<VSPR2_GetPropensityScores.Results> results;
        DVIWebService__c dviCustSetting = testDataFactory.setDVISettings();
        Consumer_Search_Web_Service__c CSCustSetting = testDataFactory.setCSSettings();
        CC_Portal__c ccPortalSettings = testDataFactory.setCCPortalSettings();        
        Test.setMock(HttpCalloutMock.Class, new VSPR2_GetPropensityCalloutMock());
        
        System.debug('Test set Mock ===');
        Account acc = new Account();
        Id rt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        acc.FirstName = 'TestDummy';
        acc.LastName = 'TheThird';
        acc.RecordTypeId = rt;
        insert acc; 
        
        MemberPlan mp = New MemberPlan();
        mp.ConsumerId__c = '306032315';
        mp.Division_ID__c = '0001';
        mp.Client_ID__c = '12006950';
        mp.primaryMemberConsumerId__c= '306032315';
        mp.Name = 'MP-100';
        mp.MemberId = acc.Id;
        insert mp;
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok;  
        
        case caseobj = new case(); 
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Vision Benefits').getRecordTypeId();
        caseObj.accountId = acc.Id;
        caseObj.Member_Plan__c = mp.Id;
        caseObj.Consumer_ID__c = mp.ConsumerId__c;
        caseObj.Client_Id__c = mp.Client_ID__c;
        caseobj.recordtypeId = rtId;
        insert caseobj;  
        
        String requestsId = caseobj.Id;
        VSPR2_GetPropensityScores props = new VSPR2_GetPropensityScores();
        List<VSPR2_GetPropensityScores.Requests> requests = new List<VSPR2_GetPropensityScores.Requests>(); 
        VSPR2_GetPropensityScores.Requests request = new VSPR2_GetPropensityScores.Requests();
        
        request.caseIdSB = requestsId;
        requests.add(request);
        Test.startTest();
         System.debug('requests ==='+requests[0].caseIdSB);
        results = VSPR2_GetPropensityScores.getPropensityScores(requests);
        System.debug('results ==='+ results[0].IPCode);
        Test.stopTest();
        
        system.assertEquals('IP', results[0].IPCode);
        system.assertEquals('Y', results[0].IPClassification);
        system.assertEquals('N/A', results[0].IPConfidence);
        system.assertEquals('retiree', results[0].IPReason);
        system.assertEquals('2', results[0].IPpriority);
        
        system.assertEquals('OON', results[0].OONCode);
        system.assertEquals('N', results[0].OONClassification);
        system.assertEquals('N/A', results[0].OONConfidence);
        system.assertEquals('ageout', results[0].OONReason);
        system.assertEquals('1', results[0].OONPriority);
    } 

    @isTest
    public static void getScoresOnCase(){
        List<VSPR2_GetPropensityScores.Results> results;
        DVIWebService__c dviCustSetting = testDataFactory.setDVISettings();
        Consumer_Search_Web_Service__c CSCustSetting = testDataFactory.setCSSettings();
        CC_Portal__c ccPortalSettings = testDataFactory.setCCPortalSettings();
        
        Account acc = new Account();
        Id rt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        acc.FirstName = 'TestDummy';
        acc.LastName = 'TheThird';
        acc.RecordTypeId = rt;
        insert acc;
        
        MemberPlan mp = New MemberPlan();
        mp.ConsumerId__c = '3060323333';
        mp.Division_ID__c = '0001';
        mp.Client_ID__c = '12006950';
        mp.primaryMemberConsumerId__c= '3060323333';
        mp.Name = 'MP-100';
        mp.MemberId = acc.Id;
        insert mp;
        
        case caseobj = new case(); 
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Vision Benefits').getRecordTypeId();
        caseObj.accountId = acc.Id;
        caseObj.Member_Plan__c = mp.Id;
        caseObj.Consumer_ID__c = mp.ConsumerId__c;
        caseObj.Client_Id__c = mp.Client_ID__c;
        caseobj.recordtypeId = rtId;
        insert caseobj;  
        
        PropensityScores__c ps = new PropensityScores__c();
        ps.Case__c = caseobj.Id;
        ps.ConsumerId__c = mp.ConsumerId__c;
        ps.Classification__c = 'Y';
        ps.Code__c = 'IP';
        ps.Reason__c = 'retiree';
        ps.Priority__c = '2';
        ps.Confidence__c = 'N/A';
        ps.PersonAccount__c = acc.Id;
        insert ps;
        
        PropensityScores__c ps2 = new PropensityScores__c();
        ps2.Case__c = caseobj.Id;
        ps2.ConsumerId__c = mp.ConsumerId__c;
        ps2.Classification__c = 'N';
        ps2.Code__c = 'OON';
        ps2.Reason__c = 'ageout';
        ps2.Priority__c = '1';
        ps2.Confidence__c = 'N/A';
        ps2.PersonAccount__c = acc.Id;
        insert ps2;
		
            
        String requestsId = caseobj.Id;
        VSPR2_GetPropensityScores props = new VSPR2_GetPropensityScores();
        List<VSPR2_GetPropensityScores.Requests> requests = new List<VSPR2_GetPropensityScores.Requests>(); 
        VSPR2_GetPropensityScores.Requests request = new VSPR2_GetPropensityScores.Requests();
        request.caseIdSB = requestsId;
        requests.add(request);
        
        Test.startTest();
        results = VSPR2_GetPropensityScores.getPropensityScores(requests); 
        Test.stopTest();
        
        system.assertEquals('IP', results[0].IPCode);
        system.assertEquals('Y', results[0].IPClassification);
        system.assertEquals('N/A', results[0].IPConfidence);
        system.assertEquals('retiree', results[0].IPReason);
        system.assertEquals('2', results[0].IPpriority);
        
        system.assertEquals('OON', results[0].OONCode);
        system.assertEquals('N', results[0].OONClassification);
        system.assertEquals('N/A', results[0].OONConfidence);
        system.assertEquals('ageout', results[0].OONReason);
        system.assertEquals('1', results[0].OONPriority);
    }
    
    @isTest
    public static void CalloutWithNoScores(){
        Test.setMock(HttpCalloutMock.Class, new VSPR2_GetPropensityCalloutNoScoresMock());
        DVIWebService__c dviCustSetting = testDataFactory.setDVISettings();
        Consumer_Search_Web_Service__c CSCustSetting = testDataFactory.setCSSettings();
        CC_Portal__c ccPortalSettings = testDataFactory.setCCPortalSettings();
        
        Account acc = new Account();
        Id rt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        acc.FirstName = 'TestDummy';
        acc.LastName = 'TheThird';
        acc.RecordTypeId = rt;
        insert acc;
        
        MemberPlan mp = New MemberPlan();
        mp.ConsumerId__c = '3060323333';
        mp.Division_ID__c = '0001';
        mp.Client_ID__c = '12006950';
        mp.primaryMemberConsumerId__c= '3060323333';
        mp.Name = 'MP-100';
        mp.MemberId = acc.Id;
        insert mp;
        
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok;
        
        case caseobj = new case(); 
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Vision Benefits').getRecordTypeId();
        caseObj.accountId = acc.Id;
        caseObj.Member_Plan__c = mp.Id;
        caseObj.Consumer_ID__c = mp.ConsumerId__c;
        caseObj.Client_Id__c = mp.Client_ID__c;
        caseobj.recordtypeId = rtId;
        insert caseobj;  
        
        String requestsId = caseobj.Id;
        VSPR2_GetPropensityScores props = new VSPR2_GetPropensityScores();
        List<VSPR2_GetPropensityScores.Requests> requests = new List<VSPR2_GetPropensityScores.Requests>(); 
        VSPR2_GetPropensityScores.Requests request = new VSPR2_GetPropensityScores.Requests();
        
        request.caseIdSB = requestsId;
        requests.add(request); 
        
        Test.startTest();
        List<VSPR2_GetPropensityScores.Results> resultsList = VSPR2_GetPropensityScores.getPropensityScores(requests);
        System.debug('2 results ==='+ resultsList[0].propensityScoreFieldIP);
        Test.stopTest();
        
        List<PropensityScores__c> updatedScores = new List<PropensityScores__c>();
        updatedScores = [SELECT Id,Offer_To__c,Channel__c,Time_Span_Begin__c FROM PropensityScores__c WHERE Case__c =: requestsId];
        
        system.assertEquals(0, updatedScores.size());
        system.assertEquals('No Offer', resultsList[0].propensityScoreFieldIP); 
        system.assertEquals('No Offer', resultsList[0].propensityScoreFieldOON); 
    }
}