src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Eyefinity_Access__c</fullName>
        <label>Eyefinity Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B - Basic</fullName>
                </value>
                <value>
                    <fullName>J - Participates in E-Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Calculation_Code__c</fullName>
        <label>Fee Calculation Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>O - Old Calculated Fee Schedule</fullName>
                </value>
                <value>
                    <fullName>N - New Calculated Fee Schedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Distribution__c</fullName>
        <description>Vision Care Practice receives one total payment or individual payments for each Business Account</description>
        <label>Payment Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Practice Account</fullName>
                </value>
                <value>
                    <fullName>Business Account(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>Practice Account Payment Method</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Business_Type__c</fullName>
        <label>Practice Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S - Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>C - Corporation</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction</fullName>
                </value>
                <value>
                    <fullName>P - Partnership</fullName>
                </value>
                <value>
                    <fullName>U - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>V - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>W - Applicant Doctor</fullName>
                </value>
                <value>
                    <fullName>X - Group Authorized Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Phone_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Location Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Vision_Care_VSP_Affiliate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Vision Care Retail Chain Account.</description>
        <inlineHelpText>Vision Care Retail Chain Account.</inlineHelpText>
        <label>Vision Care Retail Chain</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_VSP_Network_Provider__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Vision Care Member Account.</description>
        <inlineHelpText>Vision Care Member Account.</inlineHelpText>
        <label>Vision Care Network Provider</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_VSP_Other__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Vision Care Other Account Type.</description>
        <inlineHelpText>Vision Care Other Account Type.</inlineHelpText>
        <label>Vision Care Other</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Business_Account</fullName>
        <active>true</active>
        <description>A business entity doing business/providing a service or expressing an intent to do business/provide service with at least one VSP Global line of business.</description>
        <label>Business Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Practice_Account</fullName>
        <active>true</active>
        <description>A business entity representing the practice (identified by Tax ID) having a parent relationship over one or more Business Accounts.</description>
        <label>Practice Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VSP_All_Bus_Acc_Curr_Cust_Flg_Test.cls
@isTest
// Test class for VSPR_All_Bus_Acc_Curr_Cust_Flg_Sch
public class VSP_All_Bus_Acc_Curr_Cust_Flg_Test {

     @TestSetup
    static void testData(){
        Id practiceRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Practice_Account').getRecordTypeId();
        Id busAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
        VSPUtility.stopAccountTrigger = True;  ///bypass Account Trigger
        Account acc= new Account();
        acc.Name='Practice Account Name';
        acc.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
        acc.Tax_ID__c = '123456789';
        acc.Phone = '1234567890';
        acc.ShippingStreet = '123 Test Street';
        acc.ShippingCity = 'Somewhere';
        acc.ShippingState = 'CA';
        acc.ShippingPostalCode = '90210';
        acc.ShippingCountry = 'USA';
        acc.Practice_Business_Type__c = 'S - Sole Proprietor';
        acc.Fee_Calculation_Code__c = 'N - New Calculated Fee Schedule';
        acc.Payment_Method__c = 'Direct Deposit';
        acc.Payment_Distribution__c = 'Practice Account';        
        acc.RecordTypeId =  practiceRecordTypeId;        
        insert acc;
        
        Account acc1= new Account();
        acc1.Name='Bus Account Name M - VSP Member Location';       
        acc1.ParentId = acc.id;
        acc1.Fax = '123456789';
        acc1.ShippingStreet = '123 Test Street';
        acc1.ShippingCity = 'Somewhere';
        acc1.ShippingState = 'CA';
        acc1.ShippingPostalCode = '90210';
        acc1.ShippingCountry = 'USA';
        acc1.Vision_Care_Location_Phone_Number__c = '123456789';
        acc1.Eyefinity_Access__c = 'B - Basic';
        acc1.Location_Type__c = 'M - VSP Member Location';
        acc1.Tax_ID__c = '123456789';
        acc1.Vision_Care_Effective_Date__c = Date.today().addDays(-10);
        acc1.Vision_Care_End_Date__c = Date.today().addDays(-5);
        acc1.Vision_Care_VSP_Network_Provider__c = TRUE;
        acc1.Vision_Care_VSP_Affiliate__c = TRUE;                                               
        acc1.Vision_Care_VSP_Other__c = TRUE;
        acc1.VC__c = False;
        acc1.RecordTypeId =  busAccRecordTypeId; 
        
        insert acc1;  
        
        Account acc2= new Account();
        acc2.Name='Bus Account Name A - Affiliate Provider Location';       
        acc2.ParentId = acc.id;
        acc2.Fax = '123456789';
        acc2.ShippingStreet = '123 Test Street';
        acc2.ShippingCity = 'Somewhere';
        acc2.ShippingState = 'CA';
        acc2.ShippingPostalCode = '90210';
        acc2.ShippingCountry = 'USA';
        acc2.Vision_Care_Location_Phone_Number__c = '123456789';
        acc2.Eyefinity_Access__c = 'B - Basic';
        acc2.Location_Type__c = 'A - Affiliate Provider Location';
        acc2.Tax_ID__c = '123456789';
        acc2.Vision_Care_Effective_Date__c = Date.today().addDays(-10);
        acc2.Vision_Care_End_Date__c = Date.today().addDays(10);
        acc2.Vision_Care_VSP_Network_Provider__c = TRUE;
        acc2.Vision_Care_VSP_Affiliate__c = TRUE;                                               
        acc2.Vision_Care_VSP_Other__c = TRUE;
        acc2.VC__c = True;
        acc2.RecordTypeId =  busAccRecordTypeId; 
        
        insert acc2;
        
        Account acc3= new Account();
        acc3.Name='Bus Acc Name X - Client Authorized Location (GAP)';       
        acc3.ParentId = acc.id;
        acc3.Fax = '123456789';
        acc3.ShippingStreet = '123 Test Street';
        acc3.ShippingCity = 'Somewhere';
        acc3.ShippingState = 'CA';
        acc3.ShippingPostalCode = '90210';
        acc3.ShippingCountry = 'USA';
        acc3.Vision_Care_Location_Phone_Number__c = '123456789';
        acc3.Eyefinity_Access__c = 'B - Basic';
        acc3.Location_Type__c = 'X - Client Authorized Location (GAP)';
        acc3.Tax_ID__c = '123456789';
        acc3.Vision_Care_Effective_Date__c = Date.today().addDays(-10);
        acc3.Vision_Care_End_Date__c = Date.today().addDays(10);
        acc3.Vision_Care_VSP_Network_Provider__c = TRUE;
        acc3.Vision_Care_VSP_Affiliate__c = TRUE;                                               
        acc3.Vision_Care_VSP_Other__c = TRUE;
        acc3.VC__c = True;
        acc3.RecordTypeId =  busAccRecordTypeId; 
        
        insert acc3;
        
          Account acc4= new Account();
        acc4.Name='Bus Account Name M - VSP Member Location2';       
        acc4.ParentId = acc.id;
        acc4.Fax = '123456789';
        acc4.ShippingStreet = '123 Test Street';
        acc4.ShippingCity = 'Somewhere';
        acc4.ShippingState = 'CA';
        acc4.ShippingPostalCode = '90210';
        acc4.ShippingCountry = 'USA';
        acc4.Vision_Care_Location_Phone_Number__c = '123456789';
        acc4.Eyefinity_Access__c = 'B - Basic';
        acc4.Location_Type__c = 'M - VSP Member Location';
        acc4.Tax_ID__c = '123456789';
        acc4.Vision_Care_Effective_Date__c = Date.today().addDays(-10);
        acc4.Vision_Care_End_Date__c = Date.today().addDays(10);
        acc4.Vision_Care_VSP_Network_Provider__c = TRUE;
        acc4.Vision_Care_VSP_Affiliate__c = TRUE;                                               
        acc4.Vision_Care_VSP_Other__c = TRUE;
        acc4.VC__c = True;
        acc4.RecordTypeId =  busAccRecordTypeId; 
        
        insert acc4;  
    }
     public static testmethod void runBatch() {
               
        Test.startTest();
        
        String EXP = '0 0 1 * * ?';
        
        VSP_All_Bus_Acc_Curr_Cust_Flg_Sch sch = new VSP_All_Bus_Acc_Curr_Cust_Flg_Sch();
        
        system.Schedule('Business Account All Current Customer Flags Test', EXP, sch);
        
        Test.stopTest();
       
    }
}