src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision Benefits</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>D2C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Which LOB is the Opportunity for?</description>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Optics</fullName>
                </value>
                <value>
                    <fullName>Eyewear</fullName>
                </value>
                <value>
                    <fullName>Eyefinity</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Program__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product/Program</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VSPOne_Commitment_Year_1__c</fullName>
        <label>VSPOne Commitment Year 1</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VSPR32_Strategic_Agree_Chart_Cntr_Test.cls
@istest
public class VSPR32_Strategic_Agree_Chart_Cntr_Test {

    Private Static testmethod void TestStrategicController(){
        Id optyRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Strategic Agreement Opportunity').getRecordTypeId();
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        
        Account pAcc = new Account();
        pAcc.Name = 'Test Account';
        insert pAcc;
        
        Opportunity strategicOpty = new Opportunity();
        strategicOpty.AccountId = pAcc.Id;
        strategicOpty.Name = 'Test Strategic Opty '+ Date.today();
        strategicOpty.StageName = 'Prospect';
		strategicOpty.Line_of_Business__c = 'Optics';
		strategicOpty.Product_Program__c = 'TEXT';
		strategicOpty.CloseDate = Date.today();
		insert strategicOpty;
        
        Test.startTest();
        ApexPages.StandardController stdOpty = new ApexPages.StandardController(strategicOpty);
        VSPR32_Strategic_Agree_Chart_Controller myctrllr = new VSPR32_Strategic_Agree_Chart_Controller(stdOpty);
        myctrllr.EdittheSection();
        myctrllr.cancelOpty();
        myctrllr.EdittheSection();
		strategicOpty.VSPOne_Commitment_Year_1__c = 100;
		myctrllr.saveOpty();
        Test.stopTest();
        
        strategicOpty = [SELECT Id, VSPOne_Commitment_Year_1__c FROM Opportunity WHERE Account.Name = 'Test Account' LIMIT 1];
        system.assertEquals(strategicOpty.VSPOne_Commitment_Year_1__c, 100);
    }
}