src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CallerType__c</fullName>
        <label>Caller Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Retail Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Caller_Intent__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Caller Intent</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <label>Caller Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>In-Network Provider</fullName>
                </value>
                <value>
                    <fullName>Out-Of-Network Provider</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Ops</fullName>
                </value>
                <value>
                    <fullName>Retail Store</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ContactId</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MemberPlan</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Line_of_Business__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Special Order Request</fullName>
                </value>
                <value>
                    <fullName>Stock Order Status</fullName>
                </value>
                <value>
                    <fullName>Product Mapping</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
                <value>
                    <fullName>2020 Source (Affiliate)</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Cash Receipts</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>EDI Membership</fullName>
                </value>
                <value>
                    <fullName>Email Update</fullName>
                </value>
                <value>
                    <fullName>Explanation of Payment (EOP)</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Ops</fullName>
                </value>
                <value>
                    <fullName>Eyeconic USC</fullName>
                </value>
                <value>
                    <fullName>Eye Health Management (EHM)</fullName>
                </value>
                <value>
                    <fullName>Lab Opt Out</fullName>
                </value>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>HP Plan Admin</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>MetLife</fullName>
                </value>
                <value>
                    <fullName>Molina</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Office Hours Update</fullName>
                </value>
                <value>
                    <fullName>otto</fullName>
                </value>
                <value>
                    <fullName>Practice Report</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Regence</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Fees</fullName>
                </value>
                <value>
                    <fullName>Retinal Imaging</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Details__c</fullName>
        <label>Reason Details</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10 or more Dependents</fullName>
                </value>
                <value>
                    <fullName>A - C</fullName>
                </value>
                <value>
                    <fullName>Accessing Eyefinity</fullName>
                </value>
                <value>
                    <fullName>Add/Update Member/Dependent</fullName>
                </value>
                <value>
                    <fullName>Adding Dependent</fullName>
                </value>
                <value>
                    <fullName>Additional Doctor Payments</fullName>
                </value>
                <value>
                    <fullName>Add Provider / Office</fullName>
                </value>
                <value>
                    <fullName>Address</fullName>
                </value>
                <value>
                    <fullName>Add Service(s)</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>Adjustments</fullName>
                </value>
                <value>
                    <fullName>All Other Providers</fullName>
                </value>
                <value>
                    <fullName>Authorizations</fullName>
                </value>
                <value>
                    <fullName>Available Services</fullName>
                </value>
                <value>
                    <fullName>Backdating</fullName>
                </value>
                <value>
                    <fullName>Benefit Not Covered</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Benefits Description</fullName>
                </value>
                <value>
                    <fullName>Benefit Update</fullName>
                </value>
                <value>
                    <fullName>Call Handling</fullName>
                </value>
                <value>
                    <fullName>Change/Cancel</fullName>
                </value>
                <value>
                    <fullName>Change Service(s)</fullName>
                </value>
                <value>
                    <fullName>Check Eligibility</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Cigna</fullName>
                </value>
                <value>
                    <fullName>Claim/Out of Pocket Expenses</fullName>
                </value>
                <value>
                    <fullName>Claim Correction / Tracking</fullName>
                </value>
                <value>
                    <fullName>Claim Priced/Paid Date</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Client Password Reset by Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CallerType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2020Source Assistance</fullName>
                </value>
                <value>
                    <fullName>AOB/OON Provider</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Claim Payment</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Claims Adjustment</fullName>
                </value>
                <value>
                    <fullName>Client Benefits</fullName>
                </value>
                <value>
                    <fullName>Client Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Client Exceptions</fullName>
                </value>
                <value>
                    <fullName>Client Website Assistance</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Delays</fullName>
                </value>
                <value>
                    <fullName>Doctor Referral</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Eyefinity Assistance</fullName>
                </value>
                <value>
                    <fullName>Frame</fullName>
                </value>
                <value>
                    <fullName>Injury</fullName>
                </value>
                <value>
                    <fullName>Language Lines / Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Member Authorization</fullName>
                </value>
                <value>
                    <fullName>Member Benefits</fullName>
                </value>
                <value>
                    <fullName>Member Caller</fullName>
                </value>
                <value>
                    <fullName>Member Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Member Experience</fullName>
                </value>
                <value>
                    <fullName>Member Website Assistance</fullName>
                </value>
                <value>
                    <fullName>OON Caller</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Eyeconic</fullName>
        <active>true</active>
        <businessProcess>VSP Global</businessProcess>
        <description>Used to track Eyeconic cases</description>
        <label>Eyeconic</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CC_Portal__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Base_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Base URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ready_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Ready URL</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CC Portal</label>
</CustomObject>

src/objects/VspOauthToken__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Access Token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>expires_in__c</fullName>
        <label>Expires In</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>granted_at__c</fullName>
        <defaultValue>$System.OriginDateTime</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Granted At</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>tokenId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Token Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>VspOauthToken</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VspOauthToken Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VspOauthTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR3_ConsumerSearch_USC_Test.cls
@isTest
public class VSPR3_ConsumerSearch_USC_Test {
    @isTest
    public static void eyeconicSearch_EmailAndOrderNum(){
        Id paRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC cslc = new VSPR3_ConsumerSearch_USC(sc);
		cslc.eyeOrderNum = '123';
        cslc.eyeEmailAddr = 'eyemail@email.com';
        
        Account pa1 = new Account();
        pa1.RecordTypeId = paRecTypeId;
        pa1.LastName = 'last1';
        pa1.Eyeconic_Recent_Order_Number__pc = '123';
        pa1.Eyeconic_Email__pc = 'eyemail@email.com';
        insert pa1;
        
        Account pa2 = new Account();
        pa2.RecordTypeId = paRecTypeId;
        pa2.LastName = 'last2';
        pa2.Eyeconic_Recent_Order_Number__pc = '124';
        pa2.Eyeconic_Email__pc = 'eyemail@email.com';
        insert pa2;
        
        Test.startTest();
        cslc.eyeconicSearch();
        Test.stopTest();
        
        System.assertEquals(2, cslc.paList.size());
    }
    
    @isTest
    public static void eyeconicSearch_OnlyOrderNum(){
        Id paRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC cslc = new VSPR3_ConsumerSearch_USC(sc);
		cslc.eyeOrderNum = '123';
        
        Account pa1 = new Account();
        pa1.RecordTypeId = paRecTypeId;
        pa1.LastName = 'last1';
        pa1.Eyeconic_Recent_Order_Number__pc = '123';
        pa1.Eyeconic_Login_Email__pc = 'eyemail@email.com';
        insert pa1;
        
        Account pa2 = new Account();
        pa2.RecordTypeId = paRecTypeId;
        pa2.LastName = 'last2';
        pa2.Eyeconic_Recent_Order_Number__pc = '123';
        pa2.Eyeconic_Email__pc = 'eyemail@email.com';
        insert pa2;
        
        Test.startTest();
        cslc.eyeconicSearch();
        Test.stopTest();
        
        System.assertEquals(2, cslc.paList.size());
    }
    
    @isTest
    public static void eyeconicSearch_OnlyEmail(){
        Id paRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC cslc = new VSPR3_ConsumerSearch_USC(sc);
        cslc.eyeEmailAddr = 'eyemail@email.com';
        
        Account pa1 = new Account();
        pa1.RecordTypeId = paRecTypeId;
        pa1.LastName = 'last1';
        pa1.Eyeconic_Recent_Order_Number__pc = '123';
        pa1.Eyeconic_Email__pc = 'eyemail@email.com';
        insert pa1;
        
        Account pa2 = new Account();
        pa2.RecordTypeId = paRecTypeId;
        pa2.LastName = 'last2';
        pa2.Eyeconic_Recent_Order_Number__pc = '123';
        pa2.Eyeconic_Email__pc = 'eyemail@email.com';
        insert pa2;
        
        Test.startTest();
        cslc.eyeconicSearch();
        Test.stopTest();
        
        System.assertEquals(2, cslc.paList.size());
    }
    
    @isTest
    public static void eyeconicSearch_NoResults(){
        Id paRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC cslc = new VSPR3_ConsumerSearch_USC(sc);
        
        Account pa1 = new Account();
        pa1.RecordTypeId = paRecTypeId;
        pa1.LastName = 'last1';
        pa1.Eyeconic_Customer_Number__pc = '123';
        pa1.Eyeconic_Login_Email__pc = 'eyemail@email.com';
        insert pa1;
        
        Account pa2 = new Account();
        pa2.RecordTypeId = paRecTypeId;
        pa2.LastName = 'last2';
        pa2.Eyeconic_Recent_Order_Number__pc = '123';
        pa2.Eyeconic_Email__pc = 'eyemail@email.com';
        insert pa2;
        
        Test.startTest();
        cslc.eyeconicSearch();
        Test.stopTest();
        
        System.assertEquals(0, cslc.paList.size());
        system.assertEquals(1, apexpages.getMessages().size());
    }
    
    @isTest
    public static void attachToCaseWithPerson(){
        TestDataFactory.setCSSettings();
        TestDataFactory.setDVISettings();
        Id eyeRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Eyeconic').getRecordTypeId();
        Id paRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        Case testCase = new Case();
        testCase.RecordTypeId = eyeRecTypeId;
        testCase.Product__c = 'Eyeconic Ops';
        testCase.Caller_Type__c = 'Member';
        insert testCase;
        
        Account pa1 = new Account();
        pa1.RecordTypeId = paRecTypeId;
        pa1.LastName = 'last1';
        pa1.Eyeconic_Customer_Number__pc = '123';
        pa1.Eyeconic_Login_Email__pc = 'eyemail@email.com';
        insert pa1;
        
        pa1 = [SELECT PersonContactId FROM Account WHERE LastName = 'last1'];
        
        ApexPages.StandardController sc = new ApexPages.standardController(testCase);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.selectedPersonId = pa1.PersonContactId;
        
        Test.startTest();
        csUSC.attachToCase();
        Test.stopTest();
        
        testCase = [SELECT ContactId FROM Case WHERE Id =: testCase.Id];
        System.assertEquals(pa1.PersonContactId, testCase.ContactId);
    }
    
    @isTest
    public static void attachToCaseWithoutPerson(){
        TestDataFactory.setCSSettings();
        TestDataFactory.setDVISettings();
        Id eyeRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Eyeconic').getRecordTypeId();
        
        Case testCase = new Case();
        testCase.RecordTypeId = eyeRecTypeId;
        testCase.Product__c = 'Eyeconic Ops';
        testCase.Caller_Type__c = 'Member';
        insert testCase;
        
        ApexPages.StandardController sc = new ApexPages.standardController(testCase);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        
        Test.startTest();
        csUSC.attachToCase();
        Test.stopTest();
        
        testCase = [SELECT ContactId FROM Case WHERE Id =: testCase.Id];
        System.assertEquals(null, testCase.ContactId);
        System.assertEquals(1, apexpages.getMessages().size());
    }
    
    @isTest
    public static void searchRecords401(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock_Code401());
        TestDataFactory.setCSSettings();
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.dob = '03/08/1901';
        csUSC.include = false;
        csUSC.activeonly = false;
        csUSC.remdob = false;
        csUSC.firstname = 'ABCDEF';
        csUSC.lastname = 'GHIJKL';
         
        test.startTest();
        csUSC.APIsearchRecords();
        test.stopTest(); 
        
        system.assertEquals(0, csUSC.searchResults.size());
        system.assertEquals(1, apexpages.getMessages().size());
        system.assertEquals('401 Unauthorized', apexpages.getMessages().get(0).getDetail());
    }
    
    @isTest
    public static void searchRecords503(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock_Code503());
        TestDataFactory.setCSSettings();
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.dob = '03/08/1901';
        csUSC.include = false;
        csUSC.activeonly = false;
        csUSC.remdob = false;
        csUSC.firstname = 'ABCDEF';
        csUSC.lastname = 'GHIJKL';
        
        test.startTest();
        csUSC.APIsearchRecords();
        test.stopTest(); 
        
        system.assertEquals(0, csUSC.searchResults.size());
        system.assertEquals(1, apexpages.getMessages().size());
        system.assertEquals('Please try your search again. We are experiencing slow response times.', apexpages.getMessages().get(0).getDetail());
    }
    
    @isTest
    public static void searchRecords500(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock_Code500());
        TestDataFactory.setCSSettings();
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.dob = '03/08/1901';
        csUSC.include = false;
        csUSC.activeonly = false;
        csUSC.remdob = false;
        csUSC.firstname = 'ABCDEF';
        csUSC.lastname = 'GHIJKL';
        
        test.startTest();
        csUSC.APIsearchRecords();
        test.stopTest(); 
        
        system.assertEquals(0, csUSC.searchResults.size());
        system.assertEquals(1, apexpages.getMessages().size());
        system.assertEquals('No results found for your Search Criteria - ensure you entered First and LastName, Auth# or Expanded ID', apexpages.getMessages().get(0).getDetail());
    }

    @isTest
    public static void constructor(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        TestDataFactory.setDVISettings();
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok;  
        
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC cslc = new VSPR3_ConsumerSearch_USC(sc);
        cslc.contactId = '';
        cslc.midname = '';
        cslc.relation = '';
        cslc.classId = '';
        cslc.reason = '';
        cslc.reasondetail = '';
        cslc.authenticated = true;
        cslc.classification = '';
        cslc.ciscoContactId = '';
        cslc.ivrcalltype = '';
        cslc.ANI = '';
        cslc.DNIS = '';
        cslc.subject = '';
        cslc.policyid = '';
        cslc.channel = '';
        cslc.CEP = '';
        cslc.uscCaseId = '';
        
        insert caseobj;
        sc = new ApexPages.standardController(caseobj);
        cslc = new VSPR3_ConsumerSearch_USC(sc);
        
        Id uscRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        caseobj.RecordTypeId = uscRecTypeId;
        caseobj.Description = 'test';
        update caseobj;
        
        sc = new ApexPages.standardController(caseobj);
        cslc = new VSPR3_ConsumerSearch_USC(sc);
        
        caseobj = [select CallerType__c FROM Case where Id =: caseobj.id];
        system.assertEquals('Member', cslc.caseobj.CallerType__c);
    }
    
    @isTest
    public static void getCCPUrl(){
        string ccpURL;
        CC_Portal__c ccp = new CC_Portal__c();
        ccp.Name = 'Environment';
        ccp.Base_URL__c = 'https://vsp.com';
        ccp.Ready_URL__c = '/csrportal/ctiEvent/answered?SalesforceReadOnlyMode=True';        
        insert ccp;
        
        test.startTest();
        ccpURL = VSPR3_ConsumerSearch_USC.getCCPURL();
        test.stopTest();
        
        system.assertEquals('https://vsp.com', ccpURL);
    } 
     
    @isTest
    public static void searchRecords(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.dob = '03/08/1901';
        csUSC.include = false;
        csUSC.activeonly = false;
        csUSC.remdob = false;
        csUSC.firstname = 'ABCDEF';
        csUSC.lastname = 'GHIJKL';
        
        test.startTest();
        csUSC.APIsearchRecords();
        test.stopTest(); 
        
        system.assertEquals(1, csUSC.searchResults.size());
    }

    @isTest
    public static void updateCaseNoPA(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        TestDataFactory.setDVISettings();
        TestDataFactory.setCCPortalSettings();
        Caller_Intent__c ci = new Caller_Intent__c();
        ci.Name = 'Test';
        ci.Code__c = 'B9902'; 
        ci.Intent_Text__c = 'IntentText';
        insert ci;
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new case();
        Id uscRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        caseobj.RecordTypeId = uscRecTypeId;
        caseobj.Description = 'test';
        insert caseobj;
        
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.callername = 'J Smith';
        csUSC.callerintent = 'B9902';
        csUSC.dob = '03/08/1901';
        csUSC.include = true;
        csUSC.activeonly = false;
        csUSC.remdob = false;
        csUSC.firstname = 'ABCDEF';
        csUSC.lastname = 'GHIJKL';
        
        test.startTest();
        csUSC.APIsearchRecords();
        csUSC.wrapcsrList[0].isSelected = true;
        test.stopTest();
        
        csUSC.updateCase();
        caseobj = [SELECT Member_Plan__c,CallerType__c,Reason__c,Reason_Details__c,Consumer_ID__c,AccountId,PersonAccount__c,RecordTypeId,CaseNumber FROM Case WHERE Id =:caseobj.Id];
        system.assertNotEquals(null, caseobj.AccountId);
        system.assertNotEquals(null, caseobj.Member_Plan__c);
    }

    @isTest
    public static void updateCaseFoundPAandMP(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        TestDataFactory.setDVISettings();
        TestDataFactory.setCCPortalSettings();
        Caller_Intent__c ci = new Caller_Intent__c();
        ci.Name = 'Test';
        ci.Code__c = 'B9902'; 
        ci.Intent_Text__c = 'IntentText';
        insert ci;
        
        Account perAccount = new Account();
        RecordType personAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'];
        perAccount.RecordTypeId = personAccountRecordType.Id;
        perAccount.ConsumerID__c = '999999999';
        perAccount.LastName = 'lname';
        insert perAccount;
        
        MemberPlan membPlan = new MemberPlan();
        membPlan.Client_ID__c = '30023319';
        membPlan.Division_ID__c = '0061';
        membPlan.MemberId = perAccount.Id;
        membPlan.Name = 'testName';
        insert membPlan;
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new case();
        Id uscRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        caseobj.RecordTypeId = uscRecTypeId;
        caseobj.Description = 'test';
        insert caseobj;
        
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.callername = 'J Smith';
        csUSC.callerintent = 'B9902';
        csUSC.dob = '03/08/1901';
        csUSC.include = true;
        csUSC.activeonly = false;
        csUSC.remdob = false;
        csUSC.firstname = 'ABCDEF';
        csUSC.lastname = 'GHIJKL';
        
        test.startTest();
        csUSC.APIsearchRecords();
        csUSC.wrapcsrList[0].isSelected = true;
        test.stopTest();
        
        csUSC.updateCase();
        
        caseobj = [SELECT Member_Plan__c,CallerType__c,Reason__c,Reason_Details__c,Consumer_ID__c,AccountId,PersonAccount__c,RecordTypeId,CaseNumber FROM Case WHERE Id =:caseobj.Id];
        system.assertEquals(perAccount.Id, caseobj.AccountId);
        system.assertEquals(membPlan.Id, caseobj.Member_Plan__c);
    }
    
    @isTest
    public static void updateCaseFoundPANoMP(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        TestDataFactory.setDVISettings();
        TestDataFactory.setCCPortalSettings();
        Caller_Intent__c ci = new Caller_Intent__c();
        ci.Name = 'Test';
        ci.Code__c = 'B9902'; 
        ci.Intent_Text__c = 'IntentText';
        insert ci;
        
        Account perAccount = new Account();
        RecordType personAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'];
        perAccount.RecordTypeId = personAccountRecordType.Id;
        perAccount.ConsumerID__c = '999999999';
        perAccount.LastName = 'lname';
        insert perAccount;
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new case();
        Id uscRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        caseobj.RecordTypeId = uscRecTypeId;
        caseobj.Description = 'test';
        insert caseobj;
        
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.callername = 'J Smith';
        csUSC.callerintent = 'B9902';
        csUSC.dob = '03/08/1901';
        csUSC.include = true;
        csUSC.activeonly = false;
        csUSC.remdob = false;
        csUSC.firstname = 'ABCDEF';
        csUSC.lastname = 'GHIJKL';
        
        test.startTest();
        csUSC.APIsearchRecords();
        csUSC.wrapcsrList[0].isSelected = true;
        test.stopTest();
        
        csUSC.updateCase();
        
        caseobj = [SELECT Member_Plan__c,CallerType__c,Reason__c,Reason_Details__c,Consumer_ID__c,AccountId,PersonAccount__c,RecordTypeId,CaseNumber FROM Case WHERE Id =:caseobj.Id];
        system.assertEquals(perAccount.Id, caseobj.AccountId);
        system.assertNOtEquals(null, caseobj.Member_Plan__c);
    }
    
    @isTest
    public static void finalReset(){
        ConsumerSeachResults__c csr = new ConsumerSeachResults__c();
        insert csr;
        Case caseobj = new case();
        
        Test.startTest();
        VSPR3_ConsumerSearch_USC.finalReset();
        Test.stopTest();
        
        List<ConsumerSeachResults__c> csrs = new List<ConsumerSeachResults__c>();
        csrs = [SELECT Id FROM ConsumerSeachResults__c WHERE createdBy__c =: userInfo.getUserId()];
        system.assertEquals(0, csrs.size());
    }
    
    @isTest
    public static void reset(){
        Case caseobj = new Case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.memberid = '1';
        VSPR3_ConsumerSearch_USC.ConsumerId = '2';
        csUSC.dob = '01/01/1901';
        
        consumerseachresults__c csr = new consumerseachresults__c();
        insert csr;
        
        test.startTest();
        csUSC.reset();
        test.stopTest();
        
        system.assertEquals('', csUSC.memberid);
        system.assertEquals('', VSPR3_ConsumerSearch_USC.ConsumerId);
        system.assertEquals('', csUSC.dob);
    }
    
    @isTest
    public static void executeSearch(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        TestDataFactory.setDVISettings();
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new Case();
        caseobj.Consumer_ID__c = '999999999';
        insert caseobj;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.dob = '01/01/1901';
        csUSC.include = false;
        csUSC.activeOnly = true;
        csUSC.remdob = false;
        
        test.startTest();
        csUSC.executeUSCSearch();
        test.stopTest();
        
        system.debug('csUSC.searchResults = '+csUSC.searchResults);
        system.assertEquals(1, csUSC.searchResults.size());
    }
    
    @isTest
    public static void createUSCCaseCustomerCare(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        TestDataFactory.setDVISettings();
        
        Caller_Intent__c ci = new Caller_Intent__c();
        ci.Name = 'Test';
        ci.Code__c = 'B9902'; 
        ci.Intent_Text__c = 'IntentText';
        insert ci; 
        
        Test.startTest();
        VSPR3_ConsumerSearch_USC.createUSCCase('123', '9999', '55', '44', '122', 'B9902', '1112223333', '222', '18004004569', 'Phone', 'Member', 'callType');
        Test.stopTest();
        
        List<Case> newCaseList = new List<Case>();
        newCaseList = [SELECT Id,IVR_DNIS__c,IVR_ANI__c FROM Case WHERE IVR_Contact_ID__c = '123'];
        system.assertEquals(1, newCaseList.size());
    }
    
    @isTest
    public static void createUSCCaseRetail(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        TestDataFactory.setDVISettings();
        
        Caller_Intent__c ci = new Caller_Intent__c();
        ci.Name = 'Test';
        ci.Code__c = 'B9902'; 
        ci.Intent_Text__c = 'IntentText';
        insert ci;  
         
        Test.startTest();
        VSPR3_ConsumerSearch_USC.createUSCCase('123', '9999', '55', '44', '122', 'B9902', '1112223333', '222', '18442761280', 'Phone', 'Member', 'callType');
        Test.stopTest();
        
        List<Case> newCaseList = new List<Case>();
        newCaseList = [SELECT Id,IVR_DNIS__c,IVR_ANI__c FROM Case WHERE IVR_Contact_ID__c = '123'];
        system.assertEquals(1, newCaseList.size());
    }
    
    @isTest
    public static void selectConsumer(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        TestDataFactory.setCCPortalSettings();
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new case();
        ApexPages.StandardController sc = new ApexPages.standardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.dob = '03/08/1901';
        csUSC.include = true;
        csUSC.activeonly = false;
        csUSC.remdob = false;
        csUSC.firstname = 'ABCDEF';
        csUSC.lastname = 'GHIJKL';
        
        test.startTest();
        csUSC.APIsearchRecords();
        test.stopTest(); 
        
        csUSC.wrapcsrList[0].isSelected = true;
        
        csUSC.selectConsumer();
    }
    
    @isTest
    public static void getStates(){
        Case caseobj = new Case();
        ApexPages.StandardController sc = new ApexPages.StandardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        List<SelectOption> stateList = new List<SelectOption>();
        
        Test.startTest();
        stateList = csUSC.getStates();
        Test.stopTest(); 
        
        system.assertNotEquals(0, stateList.size());
    }
    
    @isTest
    public static void toggleSort(){
        Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
        TestDataFactory.setCSSettings();
        TestDataFactory.setCCPortalSettings();
        
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now();
        insert oAuthtok; 
        
        Case caseobj = new Case();
        ApexPages.StandardController sc = new ApexPages.StandardController(caseobj);
        VSPR3_ConsumerSearch_USC csUSC = new VSPR3_ConsumerSearch_USC(sc);
        csUSC.sortDir = 'asc';
        csUSC.dob = '03/08/1901';
        csUSC.include = true;
        csUSC.activeonly = false;
        csUSC.remdob = false;
        csUSC.firstname = 'ABCDEF';
        csUSC.lastname = 'GHIJKL';
        
        test.startTest();
        csUSC.APIsearchRecords();
        csUSC.toggleSort();
        test.stopTest(); 
        
        system.assertEquals('desc', csUSC.sortDir);
    }
}