src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <inlineHelpText>The relevant category for the Issue or Request.</inlineHelpText>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account/Contact Maintenance</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Credentialing/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Main client Id field. All other collection fields will pipe to this field. All logic will be based upon this field for client Id.</inlineHelpText>
        <label>Client Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Main consumer Id field. All other collection fields will pipe to this field. All logic will be based upon this field for consumer Id.</inlineHelpText>
        <label>Consumer ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ContactId</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MemberPlan</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PersonAccount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (PersonAccount)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryMemberConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PrimaryMemberConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CallerType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2020Source Assistance</fullName>
                </value>
                <value>
                    <fullName>AOB/OON Provider</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Claim Payment</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Claims Adjustment</fullName>
                </value>
                <value>
                    <fullName>Client Benefits</fullName>
                </value>
                <value>
                    <fullName>Client Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Client Exceptions</fullName>
                </value>
                <value>
                    <fullName>Client Website Assistance</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Delays</fullName>
                </value>
                <value>
                    <fullName>Doctor Referral</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Eyefinity Assistance</fullName>
                </value>
                <value>
                    <fullName>Frame</fullName>
                </value>
                <value>
                    <fullName>Injury</fullName>
                </value>
                <value>
                    <fullName>Language Lines / Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Member Authorization</fullName>
                </value>
                <value>
                    <fullName>Member Benefits</fullName>
                </value>
                <value>
                    <fullName>Member Caller</fullName>
                </value>
                <value>
                    <fullName>Member Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Member Experience</fullName>
                </value>
                <value>
                    <fullName>Member Website Assistance</fullName>
                </value>
                <value>
                    <fullName>OON Caller</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ConsumerSeachResults__c.object
<CustomObject>
    <description>Used to store results from ConsumerdB so they can be displayed and sorted using Lightning dtaaTable.  After CreateCase is called- need to delete these records.</description>
    <fields>
        <fullName>Client_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>COnsumer Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryMemberConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PrimaryMemberConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>ConsumerSeachResults</label>
    <nameField>
        <displayFormat>CS-{000}</displayFormat>
        <label>ConsumerSeachResults Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ConsumerSeachResults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MemberPlan.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Consumer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Id</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>primaryMemberConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Member Consumer Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR2_GetPropensityScores.cls
global class VSPR2_GetPropensityScores{
    @InvocableMethod
    public static List<Results> getPropensityScores(List<Requests> requests){
        String body;
        Integer responseCode;
        HTTPResponse Respbody = new HttpResponse();
        List<Results> resultsList = new List<Results>();
        
        List<PropensityScores__c> pScores = [SELECT Id, Case__c, Classification__c, Code__c, Confidence__c, ConsumerId__c, Name, PersonAccount__c, Priority__c, Reason__c,Time_Span_Begin__c,Time_Span_End__c
                                            FROM PropensityScores__c WHERE Case__c =: requests[0].caseIdSB];
        
        
        if(pScores.isEmpty()){ //if there are no scores associated with this case, call out to Consumer db and get scores
            Case caseRec = [SELECT id, accountId, member_Plan__c, consumer_Id__c, ContactId
                            FROM Case WHERE id =: requests[0].caseIdSB]; 
    
            MemberPlan mp = [SELECT ID, ConsumerId__c, Division_Id__c, Client_Id__c, PrimarymemberConsumerId__c
                             FROM MemberPlan WHERE id =: caseRec.member_Plan__c];
        
            ID personAcctId = caseRec.accountId;
            String jsonString='{"consumerId":"'+caseRec.consumer_ID__c+'","primaryMemberConsumerId":"'+mp.primaryMemberConsumerId__c+'","divIds":"'+mp.division_id__c+'","clientIds":"'+ mp.client_Id__c+'"}';
            
            HTTPResponse memResp = new HttpResponse();
            jsonString = 'PS'+jsonString;
            System.debug('jsonString ==='+jsonString);
            Respbody  = VspConsumerExpApi.getSFDCConsumers(jsonString);    
            List<PropensityScores__c> propList = new List<PropensityScores__c>();
            SYSTEM.DEBUG('API Return Body = '+ Respbody.getbody());
            responseCode =   Respbody.getStatusCode();

			if (responseCode == 200){   
				Map<String,Object> entities = (Map<String,Object>)JSON.deserializeUntyped(Respbody.getbody());
               
                Map<String,Object> entityResults = (Map<String,Object>)entities.get('entity');     
                List<Object>consumerResults = (List<Object>)entityResults.get('consumers');
                
                if(consumerResults != null){
                	Integer i=0;
                    Map<String,Object> subscriber;
                    
                    List<ConsumerSeachResults__c> csResultsList = new List<ConsumerSeachResults__c>();  //This is where we save the Search results from API
                    ConsumerSeachResults__c csResult;
                    
                    for(Object consumer:consumerResults){
                        subscriber = (Map<String,Object>)consumer;
                        
                        if(subscriber.keyset().contains('propensityScores')){
                            List<Object> propListAPI = (List<Object>)subscriber.get('propensityScores');                  
                            PropensityScores__c propRec = new PropensityScores__c();
                            Map<String,Object> propMap = new Map<String,Object>();
                            for(object p:propListAPI){  
                                propMap = (Map<String,Object>)p;
                                propRec = new PropensityScores__c();
                                propRec.consumerId__c = ''+ propMap.get('consumerId');
                                propRec.code__c = (String)propMap.get('code');
                                propRec.priority__c = ''+ propMap.get('priority');
                                propRec.classification__c = (String)propMap.get('classification');
                                propRec.confidence__c = (String)propMap.get('confidence');
                                propRec.reason__c = (String)propMap.get('reason');
                                propRec.PersonAccount__c = personAcctId;
                                propRec.Case__c = requests[0].caseIdSB;
                                propList.add(propRec);
                            }
                        }
                    }
                    
                    if(propList != null && propList.size() >0){
                        insert propList;
                        
                        List<PropensityScores__c> propSearch = [SELECT Case__c,Channel__c,Classification__c,Code__c,Confidence__c,ConsumerId__c,Id,Name,Offer_To__c,
                                                                PersonAccount__c,Priority__c,Propensity_Priority__c,Reason__c,Time_Span_Begin__c,Time_Span_End__c
                                                                FROM PropensityScores__c WHERE Case__c =: requests[0].caseIdSB];
                        
                        if(!propSearch.isEmpty()){
                            Results curResult = new Results();
                            for(PropensityScores__c pss: propSearch){ 
                                if(pss.Code__c == 'IP'){
                                    if(pss.Priority__c == '1'){
                                    	pss.Propensity_Priority__c = 'High';
                                    }else if(pss.Priority__c == '2')
                                        pss.Propensity_Priority__c = 'Medium';
                                    else{
                                        pss.Propensity_Priority__c = 'Low';
                                    }
                                    curResult.IPCode = 'IP';
                                    curResult.IPClassification = pss.Classification__c;
                                    curResult.IPConfidence = pss.Confidence__c;
                                    curResult.IPReason = pss.Reason__c;
                                    curResult.IPPriority = pss.Priority__c;
                                }
                                if(pss.Code__c == 'OON'){
                                    if(pss.Priority__c == '1'){
                                    	pss.Propensity_Priority__c = 'High';
                                    }else if(pss.Priority__c == '2')
                                        pss.Propensity_Priority__c = 'Medium';
                                    else{
                                        pss.Propensity_Priority__c = 'Low';
                                    }
                                    curResult.OONCode = 'OON';
                                    curResult.OONClassification = pss.Classification__c;
                                    curResult.OONConfidence = pss.Confidence__c;
                                    curResult.OONReason = pss.Reason__c;
                                    curResult.OONPriority = pss.Priority__c;
                                }
                            }
                            update propSearch;
                            resultsList.add(curResult);
                        }
                    }
                }
            }
        }
        else{ //scores exist on the case
            Results curResult = new Results();
            for(PropensityScores__c pScore:pScores){
                if(pScore.Code__c == 'IP'){
                    curResult.IPCode = 'IP';
                    curResult.IPClassification = pScore.Classification__c;
                    curResult.IPConfidence = pScore.Confidence__c;
                    curResult.IPReason = pScore.Reason__c;
                    curResult.IPPriority = pScore.Priority__c;
                }

                if(pScore.Code__c == 'OON'){
                    curResult.OONCode = 'OON';
                    curResult.OONClassification = pScore.Classification__c;
                    curResult.OONConfidence = pScore.Confidence__c;
                    curResult.OONReason = pScore.Reason__c;
                    curResult.OONPriority = pScore.Priority__c;
                }
            }
            resultsList.add(curResult);
        }
        
        if(!resultsList.isEmpty()){
            return resultsList;
        }
        else{
            Results curResult = new Results();
            curResult.propensityScoreFieldIP = 'No Offer';
            curResult.propensityScoreFieldOON = 'No Offer';
            resultsList.add(curResult);
            return resultsList;
        }
    }
    
    global class Requests{
        @InvocableVariable
        global String caseIdSB;
    }
    
    global class Results{
        @InvocableVariable
        global String propensityScoreFieldIP;
        @InvocableVariable
        global String IPCode;
        @InvocableVariable
        global String IPClassification;
        @InvocableVariable
        global String IPConfidence;
        @InvocableVariable
        global String IPReason;
        @InvocableVariable
        global String IPPriority;
        @InvocableVariable
        global String propensityScoreFieldOON;
        @InvocableVariable
        global String OONCode;
        @InvocableVariable
        global String OONClassification;
        @InvocableVariable
        global String OONConfidence;
        @InvocableVariable
        global String OONReason;
        @InvocableVariable
        global String OONPriority;
    }
}