src/objects/Contacts_Kit_Shipment__c.object
<CustomObject>
    <fields>
        <fullName>UPS_Tracking_Url__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>UPS Tracking</label>
        <type>Url</type>
    </fields>
    <label>Contact Lens Kit Order Shipment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contacts Kit Order Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Lens Kit Order Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The date the Product/Program ends.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Closed_Month__c</fullName>
        <description>When is the Opportunity planning on Closing?</description>
        <label>Planned Closed Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Program__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product/Program</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Order_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SAP Order Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Status__c</fullName>
        <description>Shipping status of Contact Lens Kits, to be populated via integration by SAP.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipping Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Info__c</fullName>
        <description>Tracking Info of contact lens kit populated via SAP Integration.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Info</label>
        <type>Url</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VSPR32_TestCreateConactKitShipment.cls
@isTest
public class VSPR32_TestCreateConactKitShipment {

    public static testmethod void testContactKitShipment() {
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String expectedOppId = setUpData();
        req.requestURI = '/services/apexrest/ContactKitOrderShipments/'; 
        VSPR32_ContactsKitShipmentRequest ship = new VSPR32_ContactsKitShipmentRequest();
        ship.opportunityId= expectedOppId;
        String expectedSapOrder = 'expectedSapOrder';
        ship.SapOrderNumber = expectedSapOrder;
        List<VSPR32_ContactsKitShipment> trackNumbers = new List<VSPR32_ContactsKitShipment>();
        VSPR32_ContactsKitShipment firstShipment = new VSPR32_ContactsKitShipment();
        String expectedTrackingNumber = 'expectedTrackingNumber';
        firstShipment.trackingNumber = expectedTrackingNumber;
        trackNumbers.add(firstShipment);
        ship.SapOrderShipments = trackNumbers;
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(ship));
        RestContext.request = req;
        VSPR32_CreateContactKitShipmentResource.createConatctsShipment();
        
        List<Contacts_Kit_Shipment__c> shipments = [select Name, UPS_Tracking_Url__c from Contacts_Kit_Shipment__c where Name=: expectedSapOrder];
        System.assertEquals(1, shipments.size());
        String baseUrl = 'https://www.ups.com/WebTracking?loc=en_US&tracknum=';
        System.assertEquals(baseUrl+expectedTrackingNumber, shipments.get(0).UPS_Tracking_Url__c);
        
        List<Opportunity> opps = [select Shipping_Status__c from Opportunity where Id=: expectedOppId];
        System.assertEquals('Shipped', opps.get(0).Shipping_Status__c);
    }
    
    public static testmethod void testCreateContactsOrderShipmentWithShipStatus() {
        String expectedOppId = setUpData();
        String baseUrl = 'https://www.ups.com/WebTracking?loc=en_US&tracknum=';
        System.debug(expectedOppId);
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/ContactKitOrderShipments/'; 
        VSPR32_ContactsKitShipmentRequest ship = new VSPR32_ContactsKitShipmentRequest();
        ship.opportunityId= expectedOppId;
        String expectedSapOrder = 'expectedSapOrder';
        ship.SapOrderNumber = expectedSapOrder;
        String expectedStatus = 'ExpectedStatus';
        ship.orderStatus = expectedStatus;
        List<VSPR32_ContactsKitShipment> trackNumbers = new List<VSPR32_ContactsKitShipment>();
        VSPR32_ContactsKitShipment firstShipment = new VSPR32_ContactsKitShipment();
        String expectedTrackingNumber = 'expectedTrackingNumber';
        firstShipment.trackingNumber = expectedTrackingNumber;
        trackNumbers.add(firstShipment);
        ship.SapOrderShipments = trackNumbers;
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(ship));
        RestContext.request = req;

        VSPR32_CreateContactKitShipmentResource.createConatctsShipment();
        List<Opportunity> opps = [select Shipping_Status__c, SAP_Order_Status__C, Tracking_Info__c from Opportunity where Id=: expectedOppId];
        
        System.assertEquals(expectedStatus, opps.get(0).Shipping_Status__c);
        System.assertEquals(expectedStatus, opps.get(0).SAP_Order_Status__C);
        System.assertEquals(baseUrl+expectedTrackingNumber, opps.get(0).Tracking_Info__c);
        
    }
    
    public static testmethod void testMultipleTrackingNumbers() {
        String expectedOppId = setUpData();
        String baseUrl = 'https://www.ups.com/WebTracking?loc=en_US&tracknum=';
        System.debug(expectedOppId);
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/ContactKitOrderShipments/'; 
        VSPR32_ContactsKitShipmentRequest ship = new VSPR32_ContactsKitShipmentRequest();
        ship.opportunityId= expectedOppId;
        String expectedSapOrder = 'expectedSapOrder';
        ship.SapOrderNumber = expectedSapOrder;
        String expectedStatus = 'ExpectedStatus';
        ship.orderStatus = expectedStatus;
        List<VSPR32_ContactsKitShipment> trackNumbers = new List<VSPR32_ContactsKitShipment>();
        VSPR32_ContactsKitShipment firstShipment = new VSPR32_ContactsKitShipment();
        String expectedTrackingNumber = 'expectedTrackingNumber';
        firstShipment.trackingNumber = expectedTrackingNumber;
        trackNumbers.add(firstShipment);
        
        VSPR32_ContactsKitShipment secondShipment = new VSPR32_ContactsKitShipment();
        String secondExpectedTrackingNumber = 'secondExpectedTrackingNumber';
        secondShipment.trackingNumber = secondExpectedTrackingNumber;
        trackNumbers.add(secondShipment);
        
        ship.SapOrderShipments = trackNumbers;
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(ship));
        RestContext.request = req;
        
        VSPR32_CreateContactKitShipmentResource.createConatctsShipment();
        
        List<Contacts_Kit_Shipment__c> shipments = [select Name, UPS_Tracking_Url__c from Contacts_Kit_Shipment__c where Name=: expectedSapOrder];
        System.assertEquals(2, shipments.size());

        
        List<Opportunity> opps = [select Shipping_Status__c, SAP_Order_Status__C, Tracking_Info__c from Opportunity where Id=: expectedOppId];
        
        System.assertEquals(expectedStatus, opps.get(0).Shipping_Status__c);
        System.assertEquals(expectedStatus, opps.get(0).SAP_Order_Status__C);
        // assert that comma delimited values are present for tracking from task
        System.assertEquals(baseUrl+expectedTrackingNumber+'%20'+secondExpectedTrackingNumber, opps.get(0).Tracking_Info__c);
        
    }
    
    private static String setUpData() {
       
        Account account = new Account(name='test account'); 
        insert account;
        Opportunity opp = new Opportunity(name ='Fit Kit Test opp');
        opp.AccountId = account.Id;
        opp.End_Date__c = Date.today();
        opp.CloseDate = Date.today();
        opp.Product_Program__c = 'Test';
        opp.StageName = 'Closed/Won';
        opp.Tracking_Info__c = 'http:\\google.com';
        opp.Planned_Closed_Month__c = 'May';
        insert opp;
        
        return opp.Id;
    }
}