src/objects/Premier_Benefit__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Type__c</fullName>
        <label>Benefit Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Changed from Text Area to Text (80 characters)
See SFDC-10652</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                    <default>true</default>
                    <label>Future</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premier Benefit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR32_Premier_Benefit_Status_Upd_Test.cls
//This test class needs to be deleted.

@isTest
public class VSPR32_Premier_Benefit_Status_Upd_Test {

    private static String CRON_EXP = '0 00 01 * * ?';
    
    //test method to check for active Premier Benefit
    public static testmethod void testPremierBenefitBatch(){
        
        Exception_Handler_Email__c email = new Exception_Handler_Email__c();
        email.Name = 'test@test.net';
        insert email;
        
        Premier_Benefit__c newBenefit = new Premier_Benefit__c();
        
        newBenefit.Name = 'Test Benefit';
        newBenefit.Benefit_Type__c = 'Currency';
        newBenefit.Effective_Date__c = Date.today().addDays(-1);
        newBenefit.Description__c = 'Qwerty';
        insert newBenefit;

        Premier_Benefit__c benefit = [Select Status__c from Premier_Benefit__c LIMIT 1];
        System.assertEquals('Future', benefit.Status__c);
        
        Test.startTest();
        VSPR32_Premier_Benefit_Status_Upd_Batch job = new VSPR32_Premier_Benefit_Status_Upd_Batch();
        Id jobId = Database.executeBatch(job,200);
        Test.stopTest();
        newBenefit = [Select Status__c from Premier_Benefit__c Where Name = 'Test Benefit' LIMIT 1];
        system.assertEquals(newBenefit.Status__c, 'Active');
    }
    
    @IsTest
    static void methodName2(){
        Exception_Handler_Email__c email = new Exception_Handler_Email__c();
        email.Name = 'test@test.net';
        insert email;
        
        Premier_Benefit__c newBenefit = new Premier_Benefit__c();
        
        newBenefit.Name = 'Test Benefit';
        newBenefit.Benefit_Type__c = 'Currency';
        newBenefit.Effective_Date__c = Date.today().addDays(-10);
        newBenefit.End_Date__c = System.today().addDays(-1);
        newBenefit.Description__c = 'Qwerty';
        insert newBenefit;

        Premier_Benefit__c benefit = [Select Status__c from Premier_Benefit__c LIMIT 1];
        System.assertEquals('Future', benefit.Status__c);
        
        Test.startTest();
        VSPR32_Premier_Benefit_Status_Upd_Batch job = new VSPR32_Premier_Benefit_Status_Upd_Batch();
        Id jobId = Database.executeBatch(job,200);
        Test.stopTest();
        newBenefit = [Select Status__c from Premier_Benefit__c Where Name = 'Test Benefit' LIMIT 1];
        system.assertEquals(newBenefit.Status__c, 'Inactive');
    }

    //Below test method added to cover VSPR33_PremierDailyBatch2_Sch
    //Added as part of SFDC-11988
    @IsTest
    static void methodName3(){
        
        VSPR33_PremierDailyBatch2_Sch job = new VSPR33_PremierDailyBatch2_Sch();

        Test.startTest();
        String jobId = System.schedule('Test Territory Check', CRON_EXP, job);

		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                          NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, 
                            ct.CronExpression);
        
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
    }
    //Ends here.
}