src/objects/Premier_Tier__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>A criteria in Premier Admin Tiering so that I differentiate tiers by contract.</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>Visionworks</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Blank Date = No end date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Action__c</fullName>
        <inlineHelpText>The selection of &quot;&lt;&quot; below or &quot;Top Tier&quot;, will determine the hierarchy location of where the new or edited tier needs to go in the list of existing tiers.</inlineHelpText>
        <label>Hierarchy Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;</fullName>
                </value>
                <value>
                    <fullName>Top_Tier</fullName>
                    <label>Top Tier</label>
                </value>
                <value>
                    <fullName>&gt;</fullName>
                    <isActive>false</isActive>
                    <label>&gt;</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hierarchy_Selection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If Hierarchy Action = Top Tier, Hierarchy Selection must be blank.</inlineHelpText>
        <label>Hierarchy Selection</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>The selected Hierarchy Selection Tier has a status of Inactive.</errorMessage>
            <filterItems>
                <field>Premier_Tier__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Inactive</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator, VSP Technical User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Premier_Tier__c</referenceTo>
        <relationshipLabel>Premier Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier_Name_AutoNumber__c</fullName>
        <label>Tier Name AutoNumber</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tier_Name_Id__c</fullName>
        <label>Tier Name Id</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Premier Tier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR32_Premier_Tier_Auto_Number_Test.cls
@isTest
private class VSPR32_Premier_Tier_Auto_Number_Test {
    
    @testSetup private static void createTierRecords(){
        
        Premier_Tier__c t = new Premier_Tier__c();
        t.Name = 'Ultimate Tier';
        t.Hierarchy_Action__c = 'Top_Tier';
        t.Hierarchy_Selection__c = NULL;
        t.Description__c = 'Ultimate Tier Test';
        t.Effective_Date__c = Date.today() - 5; 
        //t.End_Date__c = Date.today() +10;
        t.Status__c = 'Active';
        t.Contract_Type__c = 'Affiliate'; 
        Test.startTest();
        insert t;
        Test.stopTest();
    }
    private testmethod static void createNewTier(){
        
        try{
            Premier_Tier__c p = [SELECT Id FROM Premier_Tier__c WHERE Name = 'Ultimate Tier'];
            p.Tier_Name_AutoNumber__c = 32000;
            update p;
            
            Premier_Tier__c t = new Premier_Tier__c();
            t.Name = 'Ultimate Tier 2';
            t.Hierarchy_Action__c = '<'; 
            t.Hierarchy_Selection__c = p.Id;
            t.Description__c = 'Ultimate Tier Test';
            t.Effective_Date__c = Date.today() - 5; 
            //t.End_Date__c = Date.today() +10;
            t.Status__c = 'Active';
            t.Contract_Type__c = 'Affiliate'; //Contract Ultimate Tier
            
            Test.startTest();
            insert t;
            Test.stopTest();
        }
        catch(Exception e){
           
            System.Assert(e.getMessage().contains('The Max Number of Tiers has been met'));
        }
        
    }
    
    private testmethod static void deleteTier(){
        
        Premier_Tier__c p = [SELECT Id FROM Premier_Tier__c WHERE Name = 'Ultimate Tier'];
        Premier_Tier__c t = new Premier_Tier__c();
            t.Name = 'Ultimate Tier 2';
            t.Hierarchy_Action__c = '<'; 
            t.Hierarchy_Selection__c = p.Id;
            t.Description__c = 'Ultimate Tier Test';
            t.Effective_Date__c = Date.today() - 5; 
            //t.End_Date__c = Date.today() +10;
            t.Status__c = 'Active';
            t.Contract_Type__c = 'Affiliate'; //Contract Ultimate Tier
            
            Test.startTest();
            insert t;
        	delete t;
            Test.stopTest();
        
        p = [SELECT Id, Tier_Name_Id__c, Tier_Name_AutoNumber__c FROM Premier_Tier__c WHERE Name = 'Ultimate Tier'];
        system.assertEquals(p.Tier_Name_Id__c, 1);
        system.assertEquals(p.Tier_Name_AutoNumber__c, 2);
    }    
}