src/objects/Premier_Benefit__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Amount__c</fullName>
        <label>Benefit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Benefit_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Benefit Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Benefit_Type__c</fullName>
        <label>Benefit Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Changed from Text Area to Text (80 characters)
See SFDC-10652</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                    <default>true</default>
                    <label>Future</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premier Benefit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Premier_Tier__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>A criteria in Premier Admin Tiering so that I differentiate tiers by contract.</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>Visionworks</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Action__c</fullName>
        <inlineHelpText>The selection of &quot;&lt;&quot; below or &quot;Top Tier&quot;, will determine the hierarchy location of where the new or edited tier needs to go in the list of existing tiers.</inlineHelpText>
        <label>Hierarchy Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;</fullName>
                </value>
                <value>
                    <fullName>Top_Tier</fullName>
                    <label>Top Tier</label>
                </value>
                <value>
                    <fullName>&gt;</fullName>
                    <isActive>false</isActive>
                    <label>&gt;</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premier Tier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tier_Benefit__c.object
<CustomObject>
    <fields>
        <fullName>Benefit__c</fullName>
        <label>Benefit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Premier_Benefit__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Premier_Benefit__c.Status__c</field>
                <operation>equals</operation>
                <value>Future</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Premier_Benefit__c</referenceTo>
        <relationshipLabel>Tier Benefits</relationshipLabel>
        <relationshipName>Tier_Benefits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Premier_Tier__c</fullName>
        <label>Premier Tier</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Premier_Tier__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Premier_Tier__c.Status__c</field>
                <operation>equals</operation>
                <value>Future</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Premier_Tier__c</referenceTo>
        <relationshipLabel>Tier Benefits</relationshipLabel>
        <relationshipName>Tier_Benefits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Send_Outbound_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will be true when both Premier Tier and all Premier Benefits are either active or inactive. The checkbox will be untrue when any Premier Tier or Premier Benefits is future effective. This field is being used to trigger the outbound message for the Tier Benefit record.</description>
        <label>Send Outbound Message</label>
        <type>Checkbox</type>
    </fields>
    <label>Tier Benefit</label>
    <nameField>
        <label>Tier Benefit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tier Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/vspr33_tierBenefitOutboundBatch_test.cls
@isTest public class vspr33_tierBenefitOutboundBatch_test {

    @IsTest
    static void testmethod1(){
        
        Exception_Handler_Email__c email = new Exception_Handler_Email__c();
        email.Name = 'test@test.net';
        insert email;
        
        Premier_Tier__c pt = new Premier_Tier__c();
        pt.Name = 'Premier Test Tier 1';
        pt.Hierarchy_Action__c = 'Top_Tier';
        pt.Description__c = 'Qwerty';
        pt.Effective_Date__c = System.today();
        pt.Contract_Type__c = 'CAT2';
        insert pt;

        List<Premier_Benefit__c> pbList = new List<Premier_Benefit__c>();

        Premier_Benefit__c pb1 = new Premier_Benefit__c();
        pb1.Name = 'Premier Test Benefit 1';
        pb1.Description__c = 'Qwerty';
        pb1.Benefit_Type__c = 'Currency';
        pb1.Benefit_Amount__c = 1234;
        pb1.Effective_Date__c = System.today();
        pb1.Status__c = 'Active';
        pbList.add(pb1);
        //insert pb;

        Premier_Benefit__c pb2 = new Premier_Benefit__c();
        pb2.Name = 'Premier Test Benefit 2';
        pb2.Description__c = 'Qwerty';
        pb2.Benefit_Type__c = 'Checkbox';
        pb2.Benefit_Checkbox__c = true;
        pb2.Effective_Date__c = System.today();
        pb2.Status__c = 'Active';
        pbList.add(pb2);

        insert pbList;

        /*Premier_Tier__c pt1 = [Select id from Premier_Tier__c where Name = 'Premier Test Tier 1'];
        Premier_Benefit__c pb1 = [Select Id from Premier_Benefit__c where Name = 'Premier Test Benefit 1'];*/

        //Test.startTest();

        List<Tier_Benefit__c> tbList = new List<Tier_Benefit__c>();

        Tier_Benefit__c tb1 = new Tier_Benefit__c();
        tb1.Premier_Tier__c = pt.Id;
        tb1.Benefit__c = pbList[0].Id;
        //insert tb;
        tbList.add(tb1);

        Tier_Benefit__c tb2 = new Tier_Benefit__c();
        tb2.Premier_Tier__c = pt.Id;
        tb2.Benefit__c = pbList[1].Id;
        //insert tb;
        tbList.add(tb2);

        insert tbList;

        //Test.stopTest();

        List<Tier_Benefit__c> benefitsList = [Select id, Send_Outbound_Message__c from Tier_Benefit__c];
        //System.assertEquals(true, tb1.Send_Outbound_Message__c);

        for(Tier_Benefit__c t: benefitsList){
            System.assertEquals(true, t.Send_Outbound_Message__c);
        }

        Tier_Benefit__c tb3 = benefitsList[0];
        tb3.Send_Outbound_Message__c = false;
        update tb3;

        Test.startTest();

        vspr33_tierBenefitOutboundBatch job = new vspr33_tierBenefitOutboundBatch();
        Id jobId = Database.executeBatch(job);

        Test.stopTest();

        Tier_Benefit__c tb4 = [Select id, Send_Outbound_Message__c from Tier_Benefit__c where id = :tb3.Id];
        System.assertEquals(true, tb4.Send_Outbound_Message__c);

    }
}