src/objects/Premier_Benefit__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                    <default>true</default>
                    <label>Future</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premier Benefit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Premier_Tier__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premier Tier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tier_Benefit__c.object
<CustomObject>
    <fields>
        <fullName>Benefit__c</fullName>
        <label>Benefit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Premier_Benefit__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Premier_Benefit__c.Status__c</field>
                <operation>equals</operation>
                <value>Future</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Premier_Benefit__c</referenceTo>
        <relationshipLabel>Tier Benefits</relationshipLabel>
        <relationshipName>Tier_Benefits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Premier_Tier__c</fullName>
        <label>Premier Tier</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Premier_Tier__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Premier_Tier__c.Status__c</field>
                <operation>equals</operation>
                <value>Future</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Premier_Tier__c</referenceTo>
        <relationshipLabel>Tier Benefits</relationshipLabel>
        <relationshipName>Tier_Benefits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Send_Outbound_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will be true when both Premier Tier and all Premier Benefits are either active or inactive. The checkbox will be untrue when any Premier Tier or Premier Benefits is future effective. This field is being used to trigger the outbound message for the Tier Benefit record.</description>
        <label>Send Outbound Message</label>
        <type>Checkbox</type>
    </fields>
    <label>Tier Benefit</label>
    <nameField>
        <label>Tier Benefit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tier Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR33_outboundCheckoxCalculator.cls
public class VSPR33_outboundCheckoxCalculator {
    
    public static List<Tier_Benefit__c> premierTier(List<Tier_Benefit__c> tbList){
        Map<Id, Set<Id>> ptTb = new Map<Id, Set<Id>>();
        Map<Id, Id> tbPb = new Map<Id, Id>();
        Map<Id, Tier_Benefit__c> tbMap = new Map<Id, Tier_Benefit__c>();

        for (Tier_Benefit__c tb: tbList) {
            if (!ptTb.containsKey(tb.Premier_Tier__c)) {
                ptTb.put(tb.Premier_Tier__c, new Set<Id>{tb.Id});
            }else {
                Set<Id> s = new Set<Id>(ptTb.get(tb.Premier_Tier__c));
                s.add(tb.Id);
                ptTb.put(tb.Premier_Tier__c, s);
            }
            tbPb.put(tb.Id, tb.Benefit__c);
            tbMap.put(tb.Id, tb);
        }

        return outboundCheckoxCalculator(tbMap, ptTb, tbPb);
    }

    private static List<Tier_Benefit__c> outboundCheckoxCalculator(Map<Id, Tier_Benefit__c> tbMap, Map<Id, Set<Id>> ptTb, Map<Id, Id> tbPb){

        Set<Id> premierBenefitIdSet = new Set<Id>(tbPb.values());
        List<Premier_Tier__c> premierTierList = [Select Id, Status__c from Premier_Tier__c where Id in :ptTb.keySet() and (Status__c = 'Active' /*or Status__c = 'Inactive'*/)];
        Map<Id, Premier_Benefit__c> premierBenefitMap = new Map<Id, Premier_Benefit__c>([Select Id, Status__c from Premier_Benefit__c where Id in :premierBenefitIdSet and (Status__c = 'Active' /*or Status__c = 'Inactive'*/)]);
        List<Tier_Benefit__c> tierBenefitToUpdate = new List<Tier_Benefit__c>(); 

        for(Premier_Tier__c pt : premierTierList){
            if(ptTb.containsKey(pt.Id)){
                for (Id i : ptTb.get(pt.Id)) {
                    if (premierBenefitMap.containsKey(tbPb.get(i))) {
                        if (tbMap.get(i).Send_Outbound_Message__c != true) {
                            Tier_Benefit__c tb = tbMap.get(i);
                            tb.Send_Outbound_Message__c = true;
                            tierBenefitToUpdate.add(tb);
                        }
                    }
                }
            }
        } 
        return tierBenefitToUpdate;
    }
}