src/objects/Premier_Tier__c.object
<CustomObject>
    <label>Premier Tier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tier_Benefit__c.object
<CustomObject>
    <fields>
        <fullName>Benefit__c</fullName>
        <label>Benefit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Premier_Benefit__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Premier_Benefit__c.Status__c</field>
                <operation>equals</operation>
                <value>Future</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Premier_Benefit__c</referenceTo>
        <relationshipLabel>Tier Benefits</relationshipLabel>
        <relationshipName>Tier_Benefits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Premier_Tier__c</fullName>
        <label>Premier Tier</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Premier_Tier__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Premier_Tier__c.Status__c</field>
                <operation>equals</operation>
                <value>Future</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Premier_Tier__c</referenceTo>
        <relationshipLabel>Tier Benefits</relationshipLabel>
        <relationshipName>Tier_Benefits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Send_Outbound_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will be true when both Premier Tier and all Premier Benefits are either active or inactive. The checkbox will be untrue when any Premier Tier or Premier Benefits is future effective. This field is being used to trigger the outbound message for the Tier Benefit record.</description>
        <label>Send Outbound Message</label>
        <type>Checkbox</type>
    </fields>
    <label>Tier Benefit</label>
    <nameField>
        <label>Tier Benefit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tier Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/vspr33_tierBenefitOutboundBatch.cls
global class vspr33_tierBenefitOutboundBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    private static String query = 'Select Id, Benefit__c, Premier_Tier__c, Send_Outbound_Message__c from Tier_Benefit__c where Send_Outbound_Message__c = false';
    private static List<String> exceptionList = new List<String>();

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Tier_Benefit__c> scope) {

        List<Tier_Benefit__c> tierBenefitToUpdate = VSPR33_outboundCheckoxCalculator.premierTier(scope);

        if (!tierBenefitToUpdate.isEmpty()) {
            Database.SaveResult[] SaveResultList = Database.update(tierBenefitToUpdate, false);

            for(integer i =0; i<tierBenefitToUpdate.size();i++){
                String msg='';
                if(!SaveResultList[i].isSuccess()){
                    msg += tierBenefitToUpdate.get(i).id + '\n'+'Error: "';
                    for(Database.Error err: SaveResultList[i].getErrors()){
                        msg += err.getmessage()+'"\n\n';
                    } 
                }
                if(msg!= ''){
                    exceptionList.add(msg);
                }
            }
        }

    }

    global void finish(Database.BatchableContext BC) {
        if(!exceptionList.isEmpty() || Test.isRunningTest()){
            List<Exception_handler_Email__c> toEmailLst = Exception_handler_Email__c.getall().values();
            
            if(!toEmailLst.isEmpty()){
                String[] toAddresses = new String[]{};
                for(Exception_Handler_Email__c obj:[select Name from Exception_Handler_Email__c]){
                    toAddresses.add(obj.Name);
                }
                
                Messaging.reserveSingleEmailCapacity(2);
                
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                
                mail.setToAddresses(toAddresses);
                
                mail.setSenderDisplayName('Salesforce Support');
                
                mail.setSubject('Tier Benefit Send_Outbound_Message checkbox Batch Job Errors');
                
                mail.setBccSender(false);
                
                mail.setUseSignature(false);
                
                // Specify the text content of the email.
                mail.setPlainTextBody('Number of records failed = ' + exceptionList.size());
                
                mail.setHtmlBody('Number of records failed = ' + exceptionList.size() + '<br><br>' + exceptionList + '<br><br>');
                
                // Send the email you have created.
                if(!Test.isRunningTest()){
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                }
            }
        }

        if(!Test.isRunningTest()){
            VSPR32_Override_Bus_Acc_Tier_Grg_Batch batch = new VSPR32_Override_Bus_Acc_Tier_Grg_Batch();
            database.executeBatch(batch,50);
        }
    }
}