src/objects/VspOauthToken__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Access Token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>expires_in__c</fullName>
        <label>Expires In</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>granted_at__c</fullName>
        <defaultValue>$System.OriginDateTime</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Granted At</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>tokenId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Token Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>VspOauthToken</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VspOauthToken Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VspOauthTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VspOauthFactoryTest.cls
@isTest(SeeAllData=false)
public class VspOauthFactoryTest {

    public static testmethod void testConsumerExpCall() {
	    Test.setMock(HttpCalloutMock.class, new VspOauthCalloutMock());
        TestDataFactory.setCSSettings();
        HTTPResponse Respbody = new HttpResponse();
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now().AddDays(-1);
        insert oAuthtok; 
        //String tok = oAuthtok.access_token__c;          
                    
        String Q = '"lastName":"GHIJKL","firstName":"ABCDEF","asOfDate":"2019-10-21","dob":"19010308","includeDependents":"true","activeMembersOnly":"false","excludeDefaultDob":"false"';
        String q1 = '{'+Q+'}';
        test.startTest();
        Respbody  = VspConsumerExpApi.getSFDCConsumers(q1);  
        test.stopTest();
        System.assert(Respbody !=null);           
    }  
        
  public static testmethod void testTokenObject() {
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now().AddDays(-1);
        insert oAuthtok;
          test.startTest();
		System.assert(VspOauthTokenFactory.getTokenObject() != null);
          test.stopTest();
    }
        
    public static testmethod void testRetrieveNewtoken() {
		Test.setMock(HttpCalloutMock.class, new VspOauthCalloutMock());
		//Test.setMock(HttpCalloutMock.class, new VSPR3_ConsumerSearchMock());
         TestDataFactory.setCSSettings();
        VspOauthToken__c oAuthtok = new VspOauthToken__c(); 
        oAuthtok.tokenId__c = 'primary';
        oAuthtok.access_token__c = 'eyJhbGciOiJSUzUxMiIsImtpZCI6IkFTWU0tU1RHIiwicGkuYXRtIjoiNyJ9.eyJzY29wZSI6WyJyZWFkOnZjLnNmZGNfY29uc3VtZXJfZXhwIl0sImNsaWVudF9pZCI6InNmZGMtc29maS1hcHAiLCJpc3MiOiJodHRwczovL2xvZ2luLXJhbmNobzEuc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiYXVkIjoiaHR0cHM6Ly9hcGktc3RhZ2luZy52c3BnbG9iYWwuY29tIiwiZXhwIjoxNTcwNzE1MjY0fQ.hKZQ3N_oY8dRoU7yOGIhDouwz28kqih9SjLa-QflbrwnqGzDvj2EzRYIrK2tsFpHQ2Fucxw5ooZHKUkt-OL7Qr2bmfCnsuYFiJ_Ah59vOtJvDcUonRzHj8txxQ5EJUxtukxve7Ptj3uK62yaYfTV7G0wHzFjD0VIIsKbwXY4Gl2JOh2MkVvbaodrlj44SdhwT32IiSyYWDugLA3cvD_6_6al8ztYbG_PFO0LICH0oZjYXZ1IOQ5Tgnux3XPQ0k1Fatf8vcS7XFAYHdTi77T_-LjHKmTcGqGQm62jSsHBrNJqxlnp30lErvPcJSEii_-eD6VgHIvqp65jH4OXJ3lwNA';
        oAuthtok.expires_in__c = 1799;       
        oAuthtok.granted_at__c = DateTime.now().AddDays(-1);
        insert oAuthtok;    
            test.startTest();
        System.assert(VspOauthTokenFactory.retrieveNewToken() != null);
        System.assert(VspOauthTokenFactory.isExpired(oAuthtok) !=null);       
        VspOauthTokenFactory.updateOauthTokenForMaxTries(oAuthtok.access_token__c, 1799, 1,  3);
        VspOauthTokenFactory.updateOauthToken(oAuthtok.access_token__c, 1799) ;
            test.stopTest();     

    }   
    
    public static testmethod void testNoTokenObject() {
        VspOauthToken__c oAuthtok = new VspOauthToken__c();
		test.startTest();
        oAuthtok = VspOauthTokenFactory.getTokenObject();
        test.stopTest();
		System.assert(oAuthtok != null);
    }
}